[workspace]
resolver = "3"
default-members = [
    "ci",
    "cli",
    "types",
]

members = [
    "ci",
    "cli",
    "edge",
    "mock-registry",
    "types",
    "watcher",
]

[workspace.dependencies]
zenwave = { path = "../zenwave" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
semver = { version = "1.0", features = ["serde"] }
blake3 = "1"
hex = "0.4"
tracing = "0.1"
eyre = "0.6"
stow-types = { path = "types" }
target-lexicon = "0.12"
