//! Vendored `rustc` data the resolver needs where no rustc exists.
//!
//! A Cloudflare Worker cannot shell out to rustc, so the pieces of
//! toolchain truth a resolve consumes — the `-vV` identity line set and
//! `rustc --print cfg --target <triple>` per requested platform — are
//! recorded here. GENERATED BY `scripts/gen-rustc-data.sh` from the real
//! stable toolchain the scheduler resolves — do not edit by hand; when the
//! channel moves to a new stable the script is re-run with it.
//!
//! A resolve asks for the data of the exact `rustc_version` the task
//! carries; an unvendored version or an unvendored triple is a truthful
//! error (the caller should regenerate the table), never a guess at
//! another version's cfg values.

use std::collections::BTreeMap;

/// `rustc -vV` output for `version`, or `None` when that version's data
/// was never vendored.
#[must_use]
pub fn verbose_version(version: &str) -> Option<&'static str> {
    match version {
        "1.98.1" => Some(include_str!("../rustc-data/1.98.1/verbose.txt")),
        _ => None,
    }
}

/// `rustc --print cfg --target <triple>` lines for `version`, or `None`
/// when either the version or the triple was never vendored.
#[must_use]
pub fn cfg(version: &str, triple: &str) -> Option<Vec<String>> {
    let text: &'static str = match (version, triple) {
        ("1.98.1", "aarch64-apple-darwin") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-apple-darwin.txt")
        }
        ("1.98.1", "aarch64-apple-ios") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-apple-ios.txt")
        }
        ("1.98.1", "aarch64-apple-ios-sim") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-apple-ios-sim.txt")
        }
        ("1.98.1", "aarch64-linux-android") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-linux-android.txt")
        }
        ("1.98.1", "aarch64-unknown-linux-gnu") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-unknown-linux-gnu.txt")
        }
        ("1.98.1", "x86_64-pc-windows-msvc") => {
            include_str!("../rustc-data/1.98.1/cfg/x86_64-pc-windows-msvc.txt")
        }
        ("1.98.1", "aarch64-pc-windows-msvc") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-pc-windows-msvc.txt")
        }
        ("1.98.1", "x86_64-unknown-linux-gnu") => {
            include_str!("../rustc-data/1.98.1/cfg/x86_64-unknown-linux-gnu.txt")
        }
        ("1.98.1", "wasm32-unknown-unknown") => {
            include_str!("../rustc-data/1.98.1/cfg/wasm32-unknown-unknown.txt")
        }
        _ => return None,
    };
    Some(text.lines().map(str::to_owned).collect())
}

/// `cfg` for several triples at once, as `triple -> lines` — the shape
/// `StowResolveInput::cfg` takes.
///
/// # Errors
/// `Err(triple)` when `triple` has no vendored table.
pub fn cfg_map<'a>(
    version: &str,
    triples: impl Iterator<Item = &'a str>,
) -> Result<BTreeMap<String, Vec<String>>, &'a str> {
    let mut out = BTreeMap::new();
    for triple in triples {
        out.insert(triple.to_owned(), cfg(version, triple).ok_or(triple)?);
    }
    Ok(out)
}
