//! Vendored `rustc` data the resolver needs where no rustc exists.
//!
//! A Cloudflare Worker cannot shell out to rustc, so the pieces of
//! toolchain truth a resolve consumes — the `-vV` identity per
//! runner-family host and `rustc --print cfg --target <triple>` per
//! requested platform — are recorded here. GENERATED BY
//! `scripts/gen-rustc-data.sh` — do not edit by hand. The scheduled
//! regenerate-rustc-data job re-runs it once per runner-family OS when the
//! channel moves, so every host's `-vV` is a real rustc output of that
//! host; the worker also fetches this same tree from the repo at
//! `STOW_RUSTC_DATA_BASE_URL` for a stable newer than the bundle.
//!
//! A resolve asks for the data of the exact `rustc_version` the task
//! carries; an unvendored version, host or triple is a truthful error
//! (the caller fetches the published copy or regenerates the table),
//! never a guess at another version's values.

use std::collections::BTreeMap;

/// `rustc -vV` output for `version` built for `host`, or `None` when that
/// version/host pair was never vendored.
#[must_use]
pub fn verbose_version(version: &str, host: &str) -> Option<&'static str> {
    match (version, host) {
        ("1.98.1", "aarch64-apple-darwin") => Some(include_str!(
            "../rustc-data/1.98.1/verbose/aarch64-apple-darwin.txt"
        )),
        ("1.98.1", "x86_64-pc-windows-msvc") => Some(include_str!(
            "../rustc-data/1.98.1/verbose/x86_64-pc-windows-msvc.txt"
        )),
        ("1.98.1", "x86_64-unknown-linux-gnu") => Some(include_str!(
            "../rustc-data/1.98.1/verbose/x86_64-unknown-linux-gnu.txt"
        )),
        _ => None,
    }
}

/// `rustc --print cfg --target <triple>` lines for `version`, or `None`
/// when either the version or the triple was never vendored.
#[must_use]
pub fn cfg(version: &str, triple: &str) -> Option<Vec<String>> {
    let text: &'static str = match (version, triple) {
        ("1.98.1", "aarch64-apple-darwin") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-apple-darwin.txt")
        }
        ("1.98.1", "aarch64-apple-ios") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-apple-ios.txt")
        }
        ("1.98.1", "aarch64-apple-ios-sim") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-apple-ios-sim.txt")
        }
        ("1.98.1", "aarch64-linux-android") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-linux-android.txt")
        }
        ("1.98.1", "aarch64-pc-windows-msvc") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-pc-windows-msvc.txt")
        }
        ("1.98.1", "aarch64-unknown-linux-gnu") => {
            include_str!("../rustc-data/1.98.1/cfg/aarch64-unknown-linux-gnu.txt")
        }
        ("1.98.1", "wasm32-unknown-unknown") => {
            include_str!("../rustc-data/1.98.1/cfg/wasm32-unknown-unknown.txt")
        }
        ("1.98.1", "x86_64-pc-windows-msvc") => {
            include_str!("../rustc-data/1.98.1/cfg/x86_64-pc-windows-msvc.txt")
        }
        ("1.98.1", "x86_64-unknown-linux-gnu") => {
            include_str!("../rustc-data/1.98.1/cfg/x86_64-unknown-linux-gnu.txt")
        }
        _ => return None,
    };
    Some(text.lines().map(str::to_owned).collect())
}

/// `cfg` for several triples at once, as `triple -> lines` — the shape
/// `StowResolveInput::cfg` takes.
///
/// # Errors
/// `Err(triple)` when `triple` has no vendored table.
pub fn cfg_map<'a>(
    version: &str,
    triples: impl Iterator<Item = &'a str>,
) -> Result<BTreeMap<String, Vec<String>>, &'a str> {
    let mut out = BTreeMap::new();
    for triple in triples {
        out.insert(triple.to_owned(), cfg(version, triple).ok_or(triple)?);
    }
    Ok(out)
}
