[package]
name = "stow-admin"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "stow-admin"
path = "src/main.rs"

[dependencies]
strip-ansi-escapes = "0.2"
stow-types.workspace = true
stow-oci.workspace = true
rustls.workspace = true
zenwave.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
clap = { version = "4.5", features = ["derive"] }
cargo_metadata = "0.23"
flate2.workspace = true
tar.workspace = true
humantime = "2"
serde_html_form = "0.4"
smol = "2"
semver.workspace = true
time = { version = "0.3", features = ["formatting"] }
toml = "1"
futures-util = "0.3"
tokio = { version = "1", features = ["net", "rt", "time"] }

[lints]
workspace = true
