#!/usr/bin/env bash
# Regenerate the vendored rustc data stow-resolve needs inside the worker:
# `rustc -vV` once and `rustc --print cfg --target <triple>` for every
# CI_TARGET_TRIPLES member, plus the `resolve/src/rustc_data.rs` table that
# serves them. Run with the *stable* toolchain the scheduler resolves (see
# `stable_rustc_version` in edge/src/rust_channel.rs) — a resolve for a
# rustc version with no vendored table refuses to run.
set -euo pipefail
cd "$(dirname "$0")/.."

version="$(rustc -vV | sed -n 's/^release: //p')"
dest="resolve/rustc-data/${version}"
mkdir -p "${dest}/cfg"
rustc -vV > "${dest}/verbose.txt"

triples=(
  aarch64-apple-darwin aarch64-apple-ios aarch64-apple-ios-sim
  aarch64-linux-android aarch64-unknown-linux-gnu
  x86_64-pc-windows-msvc aarch64-pc-windows-msvc
  x86_64-unknown-linux-gnu wasm32-unknown-unknown
)
for triple in "${triples[@]}"; do
  rustc --print cfg --target "$triple" > "${dest}/cfg/${triple}.txt"
done

{
cat <<'HEADER'
//! Vendored `rustc` data the resolver needs where no rustc exists.
//!
//! A Cloudflare Worker cannot shell out to rustc, so the pieces of
//! toolchain truth a resolve consumes — the `-vV` identity line set and
//! `rustc --print cfg --target <triple>` per requested platform — are
//! recorded here. GENERATED BY `scripts/gen-rustc-data.sh` from the real
//! stable toolchain the scheduler resolves — do not edit by hand; when the
//! channel moves to a new stable the script is re-run with it.
//!
//! A resolve asks for the data of the exact `rustc_version` the task
//! carries; an unvendored version or an unvendored triple is a truthful
//! error (the caller should regenerate the table), never a guess at
//! another version's cfg values.

use std::collections::BTreeMap;

/// `rustc -vV` output for `version`, or `None` when that version's data
/// was never vendored.
#[must_use]
pub fn verbose_version(version: &str) -> Option<&'static str> {
    match version {
HEADER
printf '        "%s" => Some(include_str!("../rustc-data/%s/verbose.txt")),\n' "$version" "$version"
cat <<'VV_TAIL'
        _ => None,
    }
}

/// `rustc --print cfg --target <triple>` lines for `version`, or `None`
/// when either the version or the triple was never vendored.
#[must_use]
pub fn cfg(version: &str, triple: &str) -> Option<Vec<String>> {
    let text: &'static str = match (version, triple) {
VV_TAIL
for triple in "${triples[@]}"; do
printf '        ("%s", "%s") => {\n            include_str!("../rustc-data/%s/cfg/%s.txt")\n        }\n' \
  "$version" "$triple" "$version" "$triple"
done
cat <<'CFG_TAIL'
        _ => return None,
    };
    Some(text.lines().map(str::to_owned).collect())
}

/// `cfg` for several triples at once, as `triple -> lines` — the shape
/// `StowResolveInput::cfg` takes.
///
/// # Errors
/// `Err(triple)` when `triple` has no vendored table.
pub fn cfg_map<'a>(
    version: &str,
    triples: impl Iterator<Item = &'a str>,
) -> Result<BTreeMap<String, Vec<String>>, &'a str> {
    let mut out = BTreeMap::new();
    for triple in triples {
        out.insert(triple.to_owned(), cfg(version, triple).ok_or(triple)?);
    }
    Ok(out)
}
CFG_TAIL
} > resolve/src/rustc_data.rs

echo "vendored rustc data for ${version} under ${dest}; resolve/src/rustc_data.rs regenerated"
