#!/usr/bin/env bash
# Regenerate the vendored rustc data stow-resolve needs inside the worker:
# `rustc -vV` per runner-family host and `rustc --print cfg --target
# <triple>` for every CI_TARGET_TRIPLES member, plus the
# `resolve/src/rustc_data.rs` table that serves them. Run with the *stable*
# toolchain the scheduler resolves (see `stable_rustc_version` in
# edge/src/rust_channel.rs) — a resolve for a rustc version or host with no
# vendored table either fetches the repo-published data
# (`STOW_RUSTC_DATA_BASE_URL`) or refuses to run.
#
# `-vV` is a real `rustc -vV` of the host it ran on — the scheduled CI job
# runs this script once per runner-family OS so each host's file is genuine
# output, and files accumulate across versions and hosts. `cfg` files are
# host-independent (`--print cfg --target` reads the target spec, not the
# machine) and are regenerated on every run.
set -euo pipefail
cd "$(dirname "$0")/.."

version="$(rustc -vV | sed -n 's/^release: //p')"
host="$(rustc -vV | sed -n 's/^host: //p')"
dest="resolve/rustc-data/${version}"
mkdir -p "${dest}/verbose" "${dest}/cfg"

rustc -vV > "${dest}/verbose/${host}.txt"

triples=(
  aarch64-apple-darwin aarch64-apple-ios aarch64-apple-ios-sim
  aarch64-linux-android aarch64-unknown-linux-gnu
  x86_64-pc-windows-msvc aarch64-pc-windows-msvc
  x86_64-unknown-linux-gnu wasm32-unknown-unknown
)
for triple in "${triples[@]}"; do
  rustc --print cfg --target "$triple" > "${dest}/cfg/${triple}.txt"
done

{
cat <<'HEADER'
//! Vendored `rustc` data the resolver needs where no rustc exists.
//!
//! A Cloudflare Worker cannot shell out to rustc, so the pieces of
//! toolchain truth a resolve consumes — the `-vV` identity per
//! runner-family host and `rustc --print cfg --target <triple>` per
//! requested platform — are recorded here. GENERATED BY
//! `scripts/gen-rustc-data.sh` — do not edit by hand. The scheduled
//! regenerate-rustc-data job re-runs it once per runner-family OS when the
//! channel moves, so every host's `-vV` is a real rustc output of that
//! host; the worker also fetches this same tree from the repo at
//! `STOW_RUSTC_DATA_BASE_URL` for a stable newer than the bundle.
//!
//! A resolve asks for the data of the exact `rustc_version` the task
//! carries; an unvendored version, host or triple is a truthful error
//! (the caller fetches the published copy or regenerates the table),
//! never a guess at another version's values.

use std::collections::BTreeMap;

/// `rustc -vV` output for `version` built for `host`, or `None` when that
/// version/host pair was never vendored.
#[must_use]
pub fn verbose_version(version: &str, host: &str) -> Option<&'static str> {
    match (version, host) {
HEADER
# One match arm per verbose file actually present — earlier versions keep
# their arms, so the table accumulates.
find resolve/rustc-data -mindepth 3 -maxdepth 3 -path '*/verbose/*.txt' -print | sort -V | while read -r f; do
  ver="$(basename "$(dirname "$(dirname "$f")")")"
  h="$(basename "$f" .txt)"
  printf '        ("%s", "%s") => Some(include_str!("../rustc-data/%s/verbose/%s.txt")),\n' \
    "$ver" "$h" "$ver" "$h"
done
cat <<'VV_TAIL'
        _ => None,
    }
}

/// `rustc --print cfg --target <triple>` lines for `version`, or `None`
/// when either the version or the triple was never vendored.
#[must_use]
pub fn cfg(version: &str, triple: &str) -> Option<Vec<String>> {
    let text: &'static str = match (version, triple) {
VV_TAIL
find resolve/rustc-data -mindepth 3 -maxdepth 3 -path '*/cfg/*.txt' -print | sort -V | while read -r f; do
  ver="$(basename "$(dirname "$(dirname "$f")")")"
  t="$(basename "$f" .txt)"
  printf '        ("%s", "%s") => {\n            include_str!("../rustc-data/%s/cfg/%s.txt")\n        }\n' \
    "$ver" "$t" "$ver" "$t"
done
cat <<'CFG_TAIL'
        _ => return None,
    };
    Some(text.lines().map(str::to_owned).collect())
}

/// `cfg` for several triples at once, as `triple -> lines` — the shape
/// `StowResolveInput::cfg` takes.
///
/// # Errors
/// `Err(triple)` when `triple` has no vendored table.
pub fn cfg_map<'a>(
    version: &str,
    triples: impl Iterator<Item = &'a str>,
) -> Result<BTreeMap<String, Vec<String>>, &'a str> {
    let mut out = BTreeMap::new();
    for triple in triples {
        out.insert(triple.to_owned(), cfg(version, triple).ok_or(triple)?);
    }
    Ok(out)
}
CFG_TAIL
} > resolve/src/rustc_data.rs

echo "vendored rustc data for ${version} host ${host} under ${dest}; resolve/src/rustc_data.rs regenerated"
