//! Deterministic production-shaped scheduler database for the stow#433
//! cost gate: `queue` rows plus their dependency edges and the
//! published-slice membership the dependency gate joins, generated by
//! `INSERT … SELECT` over a recursive CTE so seeding a fresh database
//! takes seconds and every row is a pure function of its sequence
//! number. The same generator seeds both harnesses: the host-side gate
//! drives [`FixtureShape::GATE`] (10k rows — a fast pre-check inside
//! `cargo test`), and the workerd harness seeds
//! [`FixtureShape::PRODUCTION`] (100k rows) into the Durable Object for
//! the numbers that gate a merge.
//!
//! Shape, in queue-order `n`:
//! * `n <= pending_end` are `pending` — about 60% of the queue;
//! * the next ~35% are `completed`, ~2.5% `failed`, and exactly thirty
//!   `dispatched`/`running` rows — fewer than the default 45-slot
//!   dispatch limit so the alarm's claim walk actually runs;
//! * a fixed [`FixtureShape::HUMAN_LANE_ROWS`] ride the human lane,
//!   ~5% carry a future `not_before`, `first_requested_at` spreads over
//!   the trailing two days, and exactly
//!   [`FixtureShape::LAST_24H_ROWS`] sit `updated_at` inside the last
//!   24 h — the quantities a route may legitimately be bounded by, held
//!   constant across fixture sizes so the scale check sees only the
//!   stored bulk grow;
//! * every pending row gains one edge (two when `n % 3 == 0`) onto the
//!   row at `dep_n`, whose status decides the gate: completed deps sit in
//!   the published slice (met edge), anything else leaves the edge unmet
//!   and the owner blocked. Most pending rows are blocked — the
//!   production shape the alarm used to re-scan in full every pass.
//!
//! Under workerd a single request cannot write the whole fixture — one
//! 100k-row insert plus its triggers and index entries outlives a
//! Durable Object request — so every seeder takes an `n` range and the
//! probe drives them in [`SEED_BATCH_ROWS`] chunks, resuming from a
//! cursor row in `settings`. On the host
//! [`seed_production_shape`] simply loops the same chunks.

use skyzen_services::durable::DurableDb;
use stow_types::api::CI_TARGET_TRIPLES;
pub use stow_types::fixture::FixtureShape;
use stow_types::fixture::{REQUEST_FIXTURE_ENQUEUED, REQUEST_FIXTURE_FAILED};

use crate::errors::QueueError;

/// The host-gate shape — 10k rows — small enough that `cargo test`
/// stays fast. Only the host pre-check uses it; the workerd harness
/// seeds `PRODUCTION` and the 1M shape `STOW_BUDGET_SIZES` carries.
#[cfg(test)]
pub const GATE: FixtureShape = FixtureShape { queue_rows: 10_000 };

/// How the fixture's `n % len` target spread maps onto
/// [`CI_TARGET_TRIPLES`].
fn target_count() -> u32 {
    u32::try_from(CI_TARGET_TRIPLES.len()).expect("target count fits u32")
}

/// `CASE` arms assigning `expr` a target triple — generated from
/// [`CI_TARGET_TRIPLES`] so the fixture's spread follows the real list.
/// `expr` is `n` for the owner row and the dep-picker expression for an
/// edge row.
fn target_case_sql(expr: &str) -> String {
    use std::fmt::Write as _;
    let mut arms = String::new();
    for (index, target) in CI_TARGET_TRIPLES.iter().enumerate() {
        let _ = write!(arms, "WHEN {index} THEN '{target}' ");
    }
    format!("CASE ({expr}) % {} {arms}END", target_count())
}

/// Rows one seeder call covers — bounded so a probe request never holds
/// a statement (or a request's worth of trigger and index writes) large
/// enough to outlive the Durable Object runtime.
pub const SEED_BATCH_ROWS: u32 = 4_000;

/// One of the three fixture tables the seed report counts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CountedTable {
    /// `queue`.
    Queue,
    /// `queue_dependencies`.
    Dependencies,
    /// `published_slice_rows`.
    Slices,
}

impl CountedTable {
    /// The table a counter names, by its SQL name — `None` for a table
    /// the seed does not count (`requests`, `published_slices`).
    pub fn for_table(table: &str) -> Option<Self> {
        match table {
            "queue" => Some(Self::Queue),
            "queue_dependencies" => Some(Self::Dependencies),
            "published_slice_rows" => Some(Self::Slices),
            _ => None,
        }
    }
}

/// Rows the seed's three counted fixture tables hold — the totals the
/// `/budget/seed` report answers. They ride inside the seed cursor's
/// `settings` row so a chunk's advance and its tallies commit as one
/// statement: the write either lands whole or not at all, so a reply
/// lost after the commit cannot split the progress record, and a
/// replay of the call re-derives the same counters from the same
/// cursor. They are never re-derived from `COUNT(*)` per request — a
/// per-call count re-read a table that grows with the fixture, the
/// linear cost the chunked seed exists to bound.
///
/// The counters' authority differs per table, matching how the chunk
/// writes are shaped: `queue`/`slices` chunk inserts are atomic
/// `INSERT … SELECT` over a known row range, so the counter is SET to
/// the cursor position (the position is the count — a statement
/// either inserted the whole chunk or errored). `queue_dependencies`
/// inserts are `OR IGNORE` — a dep already present is skipped — so
/// its counter accumulates `SELECT changes()`, which SQLite defines
/// as the statement's direct row changes, never index or trigger
/// writes (the billed `rows_written` the backend reports counts
/// those, and cannot name records).
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct SeedCounts {
    /// Rows `queue` holds.
    pub queue: u64,
    /// Rows `queue_dependencies` holds.
    pub dependencies: u64,
    /// Rows `published_slice_rows` holds.
    pub slices: u64,
}

impl SeedCounts {
    /// The cursor's counts field — `"<queue>,<deps>,<slices>"`.
    pub fn encode(self) -> String {
        format!("{},{},{}", self.queue, self.dependencies, self.slices)
    }

    /// The counts field of a cursor — `Err` on anything but three
    /// `u64`s; the cursor is internal operator state, so a malformed
    /// field is corruption, not a compatibility case.
    pub fn decode(field: &str) -> Result<Self, QueueError> {
        let bad = || QueueError::Sql(format!("bad seed cursor counts {field:?}"));
        let mut parts = field.split(',');
        let mut number = || {
            parts
                .next()
                .ok_or_else(bad)?
                .parse::<u64>()
                .map_err(|_| bad())
        };
        let counts = Self {
            queue: number()?,
            dependencies: number()?,
            slices: number()?,
        };
        if parts.next().is_some() {
            return Err(bad());
        }
        Ok(counts)
    }

    /// `table`'s current counter.
    pub const fn get(&self, table: CountedTable) -> u64 {
        match table {
            CountedTable::Queue => self.queue,
            CountedTable::Dependencies => self.dependencies,
            CountedTable::Slices => self.slices,
        }
    }

    /// Set `table`'s counter — the position-derived totals.
    pub const fn set(&mut self, table: CountedTable, n: u64) {
        match table {
            CountedTable::Queue => self.queue = n,
            CountedTable::Dependencies => self.dependencies = n,
            CountedTable::Slices => self.slices = n,
        }
    }

    /// Add `n` inserted records to `table` — exact arithmetic: a
    /// counter that could overflow or go negative means the progress
    /// record is already wrong, which is a bug to surface, not a
    /// bound to clamp.
    pub fn add(&mut self, table: CountedTable, n: u64) -> Result<(), QueueError> {
        let next = self
            .get(table)
            .checked_add(n)
            .ok_or_else(|| QueueError::Sql("seed counter overflow".to_owned()))?;
        self.set(table, next);
        Ok(())
    }

    /// Subtract `n` deleted records — the wipe chunk's telemetry, exact
    /// like `add`.
    pub fn subtract(&mut self, table: CountedTable, n: u64) -> Result<(), QueueError> {
        let next = self
            .get(table)
            .checked_sub(n)
            .ok_or_else(|| QueueError::Sql("seed counter underflow".to_owned()))?;
        self.set(table, next);
        Ok(())
    }
}

/// Rows the last completed statement changed — SQLite's `changes()`
/// counts the statement's own record writes only: index maintenance
/// and trigger effects are excluded by definition, so unlike the
/// backend's billed `rows_written` it names real row deltas (an `OR
/// IGNORE` insert reports just the rows that landed).
pub async fn changes(db: &DurableDb) -> Result<u64, QueueError> {
    db.query("SELECT changes()")
        .fetch_scalar::<u64>()
        .await
        .map_err(|error| QueueError::Sql(format!("read changes(): {error}")))
}

/// Which stretch of the fixture a seeder call writes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeedPhase {
    /// `queue` rows — `n` runs `1..=queue_rows`.
    Queue,
    /// The every-owner edge (`dep_n = n * 7919`) — `n` runs
    /// `1..=pending_end`.
    EdgesEvery,
    /// The every-third-owner edge (`dep_n = n * 15485863`) — `n` runs
    /// `1..=pending_end`.
    EdgesThirds,
    /// `published_slice_rows` for the completed identities — `n` runs
    /// `pending_end < n <= completed_end`. The caller inserts the
    /// `published_slices` header rows once this phase completes.
    Slices,
    /// The `deps_met` recompute — `n` runs `1..=pending_end`.
    DepsMet,
}

impl SeedPhase {
    /// The phase's `n` ceiling; `next` is where the cursor goes when `n`
    /// reaches it. `pub` for the budget route's position-derived
    /// counters (an ended phase reports its range end).
    pub const fn range_end(self, shape: FixtureShape) -> u32 {
        match self {
            Self::Queue => shape.queue_rows,
            Self::EdgesEvery | Self::EdgesThirds | Self::DepsMet => shape.pending_end(),
            Self::Slices => shape.completed_end(),
        }
    }

    /// The `n` a phase resumes from.
    const fn range_start(self, shape: FixtureShape) -> u32 {
        match self {
            Self::Slices => shape.pending_end(),
            _ => 0,
        }
    }

    /// The phase the cursor advances to when this one finishes; `None`
    /// ends the seed.
    const fn next(self) -> Option<Self> {
        match self {
            Self::Queue => Some(Self::EdgesEvery),
            Self::EdgesEvery => Some(Self::EdgesThirds),
            Self::EdgesThirds => Some(Self::Slices),
            Self::Slices => Some(Self::DepsMet),
            Self::DepsMet => None,
        }
    }
}

/// The `n` domain `WITH RECURSIVE seq` generates — a chunk is always a
/// contiguous `(lo, hi]` slice of a phase's range, so the statement
/// materializes only its own rows.
fn seq_sql(lo: u32, hi: u32) -> String {
    format!("SELECT {lo} + 1 UNION ALL SELECT n + 1 FROM seq WHERE n < {hi}")
}

/// Seed `queue` rows `(lo, hi]` — every column a pure function of `n`,
/// including the `dispatch_key` the claim walk orders on and the
/// `wake_at` the alarm probes read (computed under the same
/// `dispatch_min_age_minutes` the deploy runs).
///
/// `(crate, version)` is injective in `n` — `n % 20000` carries the low
/// digits in the crate name and `n / 20000` the quotient in the
/// version — so the queue's UNIQUE identity holds at any `queue_rows`;
/// under 20000 rows the version still reads `1.0.x`, the shape the
/// drives and the 20k/100k runs were written against.
pub async fn seed_queue_chunk(
    db: &DurableDb,
    shape: FixtureShape,
    lo: u32,
    hi: u32,
    min_age_minutes: u32,
) -> Result<(), QueueError> {
    let pending_end = shape.pending_end();
    let completed_end = shape.completed_end();
    let failed_end = shape.failed_end();
    let in_flight_end = failed_end + FixtureShape::IN_FLIGHT_ROWS;
    let target_case = target_case_sql("n");
    let human_end = FixtureShape::HUMAN_LANE_ROWS;
    let lane_case = &format!("CASE WHEN n <= {human_end} THEN 'human' ELSE 'miss' END");
    let first_at = "datetime('now', '-' || (n % 2880) || ' minutes')";
    let not_before = "CASE WHEN n % 20 = 1 THEN datetime('now', '+30 minutes') \
                      ELSE '1970-01-01 00:00:00' END";
    let last_24h = FixtureShape::LAST_24H_ROWS;
    // In-flight rows model attempts with a live heartbeat: stamped ahead
    // of any lease horizon so the stale-dispatch recovery never reclaims
    // them, however long the drive runs — a fixed past offset ages out
    // mid-drive and the reclaim flips them out from under the lanes and
    // probes that measure on them. A future stamp is still a normal
    // `updated_at` write to everything else that reads it.
    // Exactly `LAST_24H_ROWS` rows inside the outcome window; the rest
    // spread 1–28 days back so the window count never tracks queue size.
    let updated_at = &format!(
        "CASE WHEN n > {failed_end} AND n <= {in_flight_end} \
              THEN datetime('now', '+1 day') \
              WHEN n <= {last_24h} THEN datetime('now', '-' || (n % 1440) || ' minutes') \
              ELSE datetime('now', '-' || (1440 + n % 38880) || ' minutes') END"
    );
    let task_id = "printf('%064x', n)";
    // `OR IGNORE` — not for collisions (the identities are injective)
    // but so a replay of a chunk whose cursor commit was lost re-runs
    // idempotently instead of stalling on its own identity keys.
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}) \
         INSERT OR IGNORE INTO queue (task_id, crate_name, version, features_json, target, rustc_version, \
                            downloads, miss_count, request_count, priority, status, lane, \
                            dispatch_attempts, not_before, first_requested_at, created_at, \
                            updated_at, host_side, preserve_lockfile, attempt, shape_requeue, \
                            github_run_id, deps_met, wake_at, dispatch_family, dispatch_key) \
         SELECT {task_id}, \
                'crate' || (n % 20000), \
                '1.' || (n / 20000) || '.' || (n % 500), \
                '[]', \
                {target_case}, \
                CASE WHEN n % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                n % 5000, 1, 1, n % 7, \
                CASE WHEN n <= {pending_end} THEN 'pending' \
                     WHEN n <= {completed_end} THEN 'completed' \
                     WHEN n <= {failed_end} THEN 'failed' \
                     WHEN n <= {in_flight_end} THEN CASE WHEN n % 2 = 0 THEN 'dispatched' \
                          ELSE 'running' END \
                     ELSE 'failed' END, \
                {lane_case}, \
                0, \
                {not_before}, \
                {first_at}, \
                {first_at}, \
                {updated_at}, \
                CASE WHEN n % 10 = 0 THEN 1 ELSE 0 END, \
                0, 1, CASE WHEN n > {pending_end} AND n <= {completed_end} THEN 1 ELSE 0 END, \
                CASE WHEN n > {in_flight_end} THEN 'run-' || n ELSE NULL END, \
                0, {wake}, {family}, {key} \
         FROM seq",
        seq = seq_sql(lo, hi),
        wake = crate::scheduler::queue::wake_at_sql(
            &format!("({lane_case})"),
            first_at,
            &format!("({not_before})"),
            min_age_minutes,
        ),
        family = crate::scheduler::queue::dispatch_family_sql(&format!("({target_case})")),
        key = crate::scheduler::queue::dispatch_key_sql(
            lane_case,
            &format!("({target_case})"),
            first_at,
            "(n % 7)",
            first_at,
            task_id,
        ),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed queue rows: {error}"))?;
    Ok(())
}

/// Seed the `phase`'s dependency edges for owner rows `(lo, hi]` — the
/// dep's identity is the same formula the `queue` seed applied at the
/// dep's own `n`.
pub async fn seed_edges_chunk(
    db: &DurableDb,
    shape: FixtureShape,
    phase: SeedPhase,
    lo: u32,
    hi: u32,
) -> Result<u64, QueueError> {
    let rows = shape.queue_rows;
    let human_end = FixtureShape::HUMAN_LANE_ROWS;
    let human_pin = human_end - FixtureShape::HUMAN_PROBE_ROWS;
    let completed_dep = shape.pending_end() + 1;
    let thirds_where = format!("WHERE n % 3 = 0 AND (n <= {human_pin} OR n > {human_end})");
    let (dep_expr, extra) = match phase {
        SeedPhase::EdgesEvery => (
            format!(
                "CASE WHEN n > {human_pin} AND n <= {human_end} \
                 THEN {completed_dep} + (n % 64) \
                 ELSE (n * 7919) % {rows} + 1 END"
            ),
            "",
        ),
        SeedPhase::EdgesThirds => (
            format!("(n * 15485863) % {rows} + 1"),
            thirds_where.as_str(),
        ),
        _ => return Err(QueueError::Sql("not an edge phase".to_owned())),
    };
    let dep_target_case = target_case_sql(&dep_expr);
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}) \
         INSERT OR IGNORE INTO queue_dependencies \
             (task_id, depends_on_task_id, dep_crate_name, dep_version, dep_features_json, \
              dep_target, dep_rustc_version, dep_host_side, dep_invocations, dep_shapes, \
              dep_side_known) \
         SELECT printf('%064x', n), \
                printf('%064x', {dep_expr}), \
                'crate' || ({dep_expr} % 20000), \
                '1.' || (({dep_expr}) / 20000) || '.' || ({dep_expr} % 500), \
                '[]', \
                {dep_target_case}, \
                CASE WHEN {dep_expr} % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                0, 1, 1, 1 \
         FROM seq {extra}",
        seq = seq_sql(lo, hi),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed dependency edges: {error}"))?;
    // The `OR IGNORE` makes the actual insert count a measured value,
    // not `(hi - lo)` — deps an earlier owner already wrote are
    // skipped.
    changes(db).await
}

/// Seed the published-slice membership of completed rows `(lo, hi]` —
/// the identity columns are the row's own `n` formula, so the chunk
/// reads nothing outside its range.
pub async fn seed_slice_chunk(db: &DurableDb, lo: u32, hi: u32) -> Result<(), QueueError> {
    let target_case = target_case_sql("n");
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}) \
         INSERT OR IGNORE INTO published_slice_rows \
             (target, rustc_version, generation, crate_name, version, features_json, \
              unit_side, unit_invocation, unit_linked) \
         SELECT {target_case}, \
                CASE WHEN n % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                1, 'crate' || (n % 20000), '1.' || (n / 20000) || '.' || (n % 500), '[]', 0, 0, 1 \
         FROM seq",
        seq = seq_sql(lo, hi),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed published slice rows: {error}"))?;
    Ok(())
}

/// The `published_slices` headers — one row per `(target, rustc)` pair
/// the completed identities carry; runs once when the `Slices` phase
/// finishes.
pub async fn seed_slice_headers(db: &DurableDb) -> Result<(), QueueError> {
    db.query(
        "INSERT OR IGNORE INTO published_slices (target, rustc_version, generation) \
         SELECT DISTINCT target, rustc_version, 1 FROM published_slice_rows",
    )
    .execute()
    .await
    .map_err(|error| format!("seed published slices: {error}"))?;
    Ok(())
}

/// Recompute `deps_met` on the pending rows `(lo, hi]` — the flag the
/// claim walk and the alarm's probes read, seeded once the edges and
/// the published membership both exist.
pub async fn seed_deps_met_chunk(db: &DurableDb, lo: u32, hi: u32) -> Result<(), QueueError> {
    db.query(&format!(
        "UPDATE queue SET deps_met = {expr}, blocked = {blocked} \
         WHERE task_id >= printf('%064x', {lo} + 1) \
           AND task_id <= printf('%064x', {hi}) \
           AND (deps_met != {expr} OR blocked != {blocked})",
        expr = crate::scheduler::queue::deps_met_sql("queue.task_id"),
        blocked = crate::scheduler::queue::blocked_sql("queue.task_id"),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed deps_met/blocked: {error}"))?;
    Ok(())
}

/// The `requests` fixture the `/requests` drives read (stow#428): one
/// `enqueued` record whose stored roots name real queue rows — a pending
/// human row (the status read's `human_lane_position` probe), a
/// completed row (`cached` arm) and a no-library root — and one `failed`
/// record, the backstop's terminal state. Inserted when the `Queue`
/// phase finishes so the ids it names exist.
pub async fn seed_requests(db: &DurableDb, shape: FixtureShape) -> Result<(), QueueError> {
    let pending_root =
        stow_types::fixture::task_hex_id(u64::from(FixtureShape::HUMAN_LANE_ROWS - 5));
    // Row 5 stays clear of the purge drive's row-0/1 deletes, which run
    // before `GET /requests/{id}` re-probes this root.
    let completed_root = stow_types::fixture::task_hex_id(u64::from(shape.completed_row(5)));
    let outcome = serde_json::json!([
        {
            "target": CI_TARGET_TRIPLES[0],
            "task_id": pending_root,
            "cached": false,
            "was_queued": false,
        },
        {
            "target": CI_TARGET_TRIPLES[1],
            "task_id": completed_root,
            "cached": false,
            "was_queued": true,
        },
        {
            "target": CI_TARGET_TRIPLES[2],
            "task_id": null,
            "cached": false,
            "was_queued": false,
        },
    ])
    .to_string();
    db.query(
        "INSERT OR IGNORE INTO requests (request_id, attempt, crate_name, version, features_json, \
         rustc_version, state, dispatched_at, github_run_id, github_run_url, \
         outcome_json, error) \
         VALUES (?, 1, 'serde', '1.0.0', '[]', '1.86.0', 'enqueued', 0, \
                 '42', 'https://github.com/water-rs/stow/actions/runs/42', ?, NULL), \
                (?, 2, 'clap', '1.0.0', '[]', '1.86.0', 'failed', 0, \
                 '43', 'https://github.com/water-rs/stow/actions/runs/43', NULL, ?)",
    )
    .bind(REQUEST_FIXTURE_ENQUEUED)
    .bind(outcome)
    .bind(REQUEST_FIXTURE_FAILED)
    .bind("resolve run concluded 'failure' (https://github.com/water-rs/stow/actions/runs/43)")
    .execute()
    .await
    .map_err(|error| format!("seed request rows: {error}"))?;
    Ok(())
}

/// The counted table a phase's chunk writes — the counter the cursor
/// advances for it. `DepsMet` only updates, so it reports no table.
pub const fn counted_table(phase: SeedPhase) -> Option<CountedTable> {
    match phase {
        SeedPhase::Queue => Some(CountedTable::Queue),
        SeedPhase::EdgesEvery | SeedPhase::EdgesThirds => Some(CountedTable::Dependencies),
        SeedPhase::Slices => Some(CountedTable::Slices),
        SeedPhase::DepsMet => None,
    }
}

/// What one [`seed_batch`] chunk call did.
#[derive(Debug, Clone, Copy)]
pub struct SeedStep {
    /// The phase the cursor resumes from (the next phase once this one
    /// finished).
    pub phase: SeedPhase,
    /// The `n` the cursor resumes at.
    pub n: u32,
    /// The seed is finished.
    pub done: bool,
    /// The chunk wrote or updated fixture state (its range was
    /// non-empty at this `n`).
    pub wrote: bool,
    /// Edge records the chunk actually inserted — measured by
    /// `SELECT changes()`, the only counter a position cannot derive,
    /// since `OR IGNORE` skips deps an earlier owner already wrote.
    /// Zero outside the edge phases.
    pub edges_written: u64,
}

/// Seed one `(n, n + batch]` chunk of `phase` and return where the seed
/// resumes — the next phase (or `None` once `DepsMet` finishes).
pub async fn seed_batch(
    db: &DurableDb,
    shape: FixtureShape,
    phase: SeedPhase,
    n: u32,
    batch: u32,
    min_age_minutes: u32,
) -> Result<SeedStep, QueueError> {
    let hi = (n + batch).min(phase.range_end(shape));
    let mut edges_written = 0u64;
    let wrote = hi > n;
    if wrote {
        match phase {
            SeedPhase::Queue => {
                seed_queue_chunk(db, shape, n, hi, min_age_minutes).await?;
                if hi >= phase.range_end(shape) {
                    seed_requests(db, shape).await?;
                }
            }
            SeedPhase::EdgesEvery | SeedPhase::EdgesThirds => {
                edges_written = seed_edges_chunk(db, shape, phase, n, hi).await?;
            }
            SeedPhase::Slices => {
                seed_slice_chunk(db, n.max(phase.range_start(shape)), hi).await?;
                if hi >= phase.range_end(shape) {
                    seed_slice_headers(db).await?;
                }
            }
            SeedPhase::DepsMet => seed_deps_met_chunk(db, n, hi).await?,
        }
    }
    let (next_phase, next_n, done) = if hi >= phase.range_end(shape) {
        phase.next().map_or((phase, hi, true), |next| {
            (next, next.range_start(shape), false)
        })
    } else {
        (phase, hi, false)
    };
    Ok(SeedStep {
        phase: next_phase,
        n: next_n,
        done,
        wrote,
        edges_written,
    })
}

/// Seed the whole fixture on the host path — the same chunks the
/// workerd probe writes, looped until the seed reports done.
///
/// # Errors
/// Returns `QueueError::Sql` if any seed statement fails.
#[cfg(test)]
pub async fn seed_production_shape(
    db: &DurableDb,
    shape: &FixtureShape,
    min_age_minutes: u32,
) -> Result<(), QueueError> {
    let mut phase = SeedPhase::Queue;
    let mut n = phase.range_start(*shape);
    loop {
        let step = seed_batch(db, *shape, phase, n, SEED_BATCH_ROWS, min_age_minutes).await?;
        if step.done {
            return Ok(());
        }
        phase = step.phase;
        n = step.n;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scheduler::test_db::memory_db;

    /// The cursor's counts field round-trips and rejects anything that
    /// is not three `u64`s — it is internal operator state, so a
    /// malformed field is corruption, never a legacy shape.
    #[test]
    fn seed_counts_codec() {
        let counts = SeedCounts {
            queue: 1_000_000,
            dependencies: 799_994,
            slices: 350_000,
        };
        assert_eq!(
            SeedCounts::decode(&counts.encode()).expect("round-trip"),
            counts
        );
        for bad in ["", "1,2", "1,2,3,4", "a,2,3", "1,2,3x", "1,2,3 "] {
            assert!(SeedCounts::decode(bad).is_err(), "{bad:?} decoded");
        }
    }

    /// `SELECT changes()` names the records a statement actually wrote —
    /// the counter source the backend's billed `rows_written` cannot
    /// be, since workerd folds index writes into it. A replayed `OR
    /// IGNORE` chunk reports only the rows it inserted: the first run
    /// writes the whole range, a partial re-run only the unwritten
    /// tail, and a full replay nothing at all.
    #[tokio::test]
    async fn edge_chunk_counts_only_inserted_records() {
        let db = memory_db().await.expect("memory db");
        let shape = FixtureShape { queue_rows: 400 };
        let written = seed_edges_chunk(&db, shape, SeedPhase::EdgesEvery, 0, 200)
            .await
            .expect("edges");
        assert_eq!(written, 200, "a fresh chunk inserts its whole range");
        let resumed = seed_edges_chunk(&db, shape, SeedPhase::EdgesEvery, 100, 300)
            .await
            .expect("overlapping chunk");
        assert_eq!(
            resumed, 100,
            "an overlapping chunk counts only its unwritten tail"
        );
        let replay = seed_edges_chunk(&db, shape, SeedPhase::EdgesEvery, 0, 300)
            .await
            .expect("replay");
        assert_eq!(replay, 0, "a replay inserts nothing");
        let rows: i64 = db
            .query("SELECT count(*) FROM queue_dependencies")
            .fetch_scalar()
            .await
            .expect("count");
        assert_eq!(rows, 300, "the table holds exactly the written union");
    }

    /// Queue and slice chunks replay idempotently too — the derived
    /// position counters stay exact after a cursor-commit loss because
    /// the re-run completes the same range.
    #[tokio::test]
    async fn queue_and_slice_chunks_replay_idempotently() {
        let db = memory_db().await.expect("memory db");
        let shape = FixtureShape { queue_rows: 400 };
        seed_queue_chunk(&db, shape, 0, 100, 0)
            .await
            .expect("queue chunk");
        seed_queue_chunk(&db, shape, 0, 100, 0)
            .await
            .expect("queue replay");
        let rows: i64 = db
            .query("SELECT count(*) FROM queue")
            .fetch_scalar()
            .await
            .expect("count");
        assert_eq!(rows, 100, "a replayed queue chunk adds nothing");
        seed_slice_chunk(&db, 200, 300).await.expect("slice chunk");
        seed_slice_chunk(&db, 200, 300).await.expect("slice replay");
        let rows: i64 = db
            .query("SELECT count(*) FROM published_slice_rows")
            .fetch_scalar()
            .await
            .expect("count");
        assert_eq!(rows, 100, "a replayed slice chunk adds nothing");
    }
}
