//! Deterministic production-shaped scheduler database for the stow#433
//! cost gate: `queue` rows plus their dependency edges and the
//! published-slice membership the dependency gate joins, generated by
//! `INSERT … SELECT` over a recursive CTE so seeding a fresh database
//! takes seconds and every row is a pure function of its sequence
//! number. The same generator seeds both harnesses: the host-side gate
//! drives [`FixtureShape::GATE`] (10k rows — a fast pre-check inside
//! `cargo test`), and the workerd harness seeds
//! [`FixtureShape::PRODUCTION`] (100k rows) into the Durable Object for
//! the numbers that gate a merge.
//!
//! Shape, in queue-order `n`:
//! * `n <= pending_end` are `pending` — about 60% of the queue;
//! * the next ~35% are `completed`, ~2.5% `failed`, and exactly thirty
//!   `dispatched`/`running` rows — fewer than the default 45-slot
//!   dispatch limit so the alarm's claim walk actually runs;
//! * a fixed [`FixtureShape::HUMAN_LANE_ROWS`] ride the human lane,
//!   ~5% carry a future `not_before`, `first_requested_at` spreads over
//!   the trailing two days, and exactly
//!   [`FixtureShape::LAST_24H_ROWS`] sit `updated_at` inside the last
//!   24 h — the quantities a route may legitimately be bounded by, held
//!   constant across fixture sizes so the scale check sees only the
//!   stored bulk grow;
//! * every pending row gains one edge (two when `n % 3 == 0`) onto the
//!   row at `dep_n`, whose status decides the gate: completed deps sit in
//!   the published slice (met edge), anything else leaves the edge unmet
//!   and the owner blocked. Most pending rows are blocked — the
//!   production shape the alarm used to re-scan in full every pass.
//!
//! Under workerd a single request cannot write the whole fixture — one
//! 100k-row insert plus its triggers and index entries outlives a
//! Durable Object request — so every seeder takes an `n` range and the
//! probe drives them in [`SEED_BATCH_ROWS`] chunks, resuming from a
//! cursor row in `settings`. On the host
//! [`seed_production_shape`] simply loops the same chunks.

use skyzen_services::durable::DurableDb;
use stow_types::api::CI_TARGET_TRIPLES;

use crate::errors::QueueError;

/// The row-count shape the seeded database takes. Every split below is
/// derived from `queue_rows`, so the host gate and the workerd harness
/// share one shape at two scales: the workerd pass runs it at 20k and
/// 100k (`STOW_BUDGET_SIZES` in `scripts/scheduler-budget.sh`) and a
/// drive whose counters grow with the stored bulk fails — only
/// `queue_rows` moves, so every quantity a route may legitimately be
/// bounded by is held constant across the two shapes.
#[derive(Debug, Clone, Copy)]
pub struct FixtureShape {
    /// Total `queue` rows to seed.
    pub queue_rows: u32,
}

impl FixtureShape {
    /// The production shape — 100k rows — the workerd harness seeds by
    /// default (`STOW_BUDGET_SIZES` adds the 20k shape to the pair).
    pub const PRODUCTION: Self = Self {
        queue_rows: 100_000,
    };
    /// The host-gate shape — 10k rows — small enough that `cargo test`
    /// stays fast. Only the host pre-check uses it; the workerd harness
    /// seeds `PRODUCTION` and the 20k shape `STOW_BUDGET_SIZES` carries.
    #[cfg(test)]
    pub const GATE: Self = Self { queue_rows: 10_000 };
    /// The in-flight set — `dispatched`/`running` rows — capped so the
    /// dispatch limit still leaves slots for the claim pass to fill.
    /// Held constant across fixture sizes: the alarm's claim is bounded
    /// by this plus the dispatch cap, not by the queue.
    const IN_FLIGHT_ROWS: u32 = 30;
    /// Pending rows on the human lane — held constant so a lane-position
    /// probe reads the same depth at every fixture size.
    pub const HUMAN_LANE_ROWS: u32 = 2_000;
    /// The human lane's tail rows pin their single edge at a completed
    /// row, so they are unblocked at every fixture size — a lane-status
    /// drive can name a fixed id whose lane-position probe always runs
    /// instead of silently skipping when a size-dependent edge set
    /// flips `blocked`.
    pub const HUMAN_PROBE_ROWS: u32 = 16;
    /// Rows `updated_at` inside the last 24 h — held constant: an
    /// `/admin/status` outcome count is legitimately bounded by 24 h
    /// throughput, which the scale check must not let grow with the
    /// stored bulk.
    const LAST_24H_ROWS: u32 = 3_000;

    /// Rows `1..=pending_end` are `pending` — 60% of the queue.
    pub const fn pending_end(self) -> u32 {
        self.queue_rows / 10 * 6
    }

    /// Rows `pending_end < n <= completed_end` are `completed` — 35%.
    pub const fn completed_end(self) -> u32 {
        self.queue_rows / 20 * 19
    }

    /// Rows `completed_end < n <= failed_end` are `failed` — 2.5%.
    pub const fn failed_end(self) -> u32 {
        self.queue_rows / 40 * 39
    }

    /// A `pending` row id — `n` indexes the pending group.
    pub const fn pending_row(n: u32) -> u32 {
        n
    }

    /// A `completed` row id — `k` indexes the completed group.
    pub const fn completed_row(self, k: u32) -> u32 {
        self.pending_end() + 1 + k
    }

    /// A `failed` row id — `k` indexes the failed group.
    pub const fn failed_row(self, k: u32) -> u32 {
        self.completed_end() + 1 + k
    }

    /// The one `dispatched` row the completion drive reports.
    pub const fn dispatched_row(self) -> u32 {
        self.failed_end() + 2
    }

    /// The one `running` row the run-completion drive reports.
    pub const fn running_row(self) -> u32 {
        self.failed_end() + 3
    }

    /// A `completed` dep for the submit batch's `depends_on` — `k` picks
    /// inside the completed group so the dep's node is real and
    /// published.
    pub const fn dep_row(self, k: u32) -> u32 {
        self.pending_end() + 1 + k % (self.completed_end() - self.pending_end())
    }

    /// The first `n % TARGETS == target_index` row inside the completed
    /// group — where the slice's live members start. Strictly greater
    /// than `pending_end`: the boundary row itself is still `pending`.
    pub fn slice_first_row(self, target_index: u32) -> u32 {
        let targets = target_count();
        let offset = (targets + target_index - self.pending_end() % targets) % targets;
        self.pending_end() + if offset == 0 { targets } else { offset }
    }

    /// How many live members the `(CI_TARGET_TRIPLES[target_index],
    /// '1.85.0')` slice carries — the completed rows whose `n` lands on
    /// the target index (and `n % 9 == 0` implies `n % 3 == 0`, the
    /// 1.85.0 rustc arm).
    pub fn slice_live_rows(self, target_index: u32) -> u32 {
        let first = self.slice_first_row(target_index);
        if first > self.completed_end() {
            return 0;
        }
        (self.completed_end() - first) / target_count() + 1
    }
}

/// How the fixture's `n % len` target spread maps onto
/// [`CI_TARGET_TRIPLES`].
fn target_count() -> u32 {
    u32::try_from(CI_TARGET_TRIPLES.len()).expect("target count fits u32")
}

/// `CASE` arms assigning `expr` a target triple — generated from
/// [`CI_TARGET_TRIPLES`] so the fixture's spread follows the real list.
/// `expr` is `n` for the owner row and the dep-picker expression for an
/// edge row.
fn target_case_sql(expr: &str) -> String {
    use std::fmt::Write as _;
    let mut arms = String::new();
    for (index, target) in CI_TARGET_TRIPLES.iter().enumerate() {
        let _ = write!(arms, "WHEN {index} THEN '{target}' ");
    }
    format!("CASE ({expr}) % {} {arms}END", target_count())
}

/// Rows one seeder call covers — bounded so a probe request never holds
/// a statement (or a request's worth of trigger and index writes) large
/// enough to outlive the Durable Object runtime.
pub const SEED_BATCH_ROWS: u32 = 4_000;

/// Which stretch of the fixture a seeder call writes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeedPhase {
    /// `queue` rows — `n` runs `1..=queue_rows`.
    Queue,
    /// The every-owner edge (`dep_n = n * 7919`) — `n` runs
    /// `1..=pending_end`.
    EdgesEvery,
    /// The every-third-owner edge (`dep_n = n * 15485863`) — `n` runs
    /// `1..=pending_end`.
    EdgesThirds,
    /// `published_slice_rows` for the completed identities — `n` runs
    /// `pending_end < n <= completed_end`. The caller inserts the
    /// `published_slices` header rows once this phase completes.
    Slices,
    /// The `deps_met` recompute — `n` runs `1..=pending_end`.
    DepsMet,
}

impl SeedPhase {
    /// The phase's `n` ceiling; `next` is where the cursor goes when `n`
    /// reaches it.
    const fn range_end(self, shape: FixtureShape) -> u32 {
        match self {
            Self::Queue => shape.queue_rows,
            Self::EdgesEvery | Self::EdgesThirds | Self::DepsMet => shape.pending_end(),
            Self::Slices => shape.completed_end(),
        }
    }

    /// The `n` a phase resumes from.
    const fn range_start(self, shape: FixtureShape) -> u32 {
        match self {
            Self::Slices => shape.pending_end(),
            _ => 0,
        }
    }

    /// The phase the cursor advances to when this one finishes; `None`
    /// ends the seed.
    const fn next(self) -> Option<Self> {
        match self {
            Self::Queue => Some(Self::EdgesEvery),
            Self::EdgesEvery => Some(Self::EdgesThirds),
            Self::EdgesThirds => Some(Self::Slices),
            Self::Slices => Some(Self::DepsMet),
            Self::DepsMet => None,
        }
    }
}

/// The `n` domain `WITH RECURSIVE seq` generates — a chunk is always a
/// contiguous `(lo, hi]` slice of a phase's range, so the statement
/// materializes only its own rows.
fn seq_sql(lo: u32, hi: u32) -> String {
    format!("SELECT {lo} + 1 UNION ALL SELECT n + 1 FROM seq WHERE n < {hi}")
}

/// Seed `queue` rows `(lo, hi]` — every column a pure function of `n`,
/// including the `dispatch_key` the claim walk orders on and the
/// `wake_at` the alarm probes read (computed under the same
/// `dispatch_min_age_minutes` the deploy runs).
pub async fn seed_queue_chunk(
    db: &DurableDb,
    shape: FixtureShape,
    lo: u32,
    hi: u32,
    min_age_minutes: u32,
) -> Result<(), QueueError> {
    let pending_end = shape.pending_end();
    let completed_end = shape.completed_end();
    let failed_end = shape.failed_end();
    let in_flight_end = failed_end + FixtureShape::IN_FLIGHT_ROWS;
    let target_case = target_case_sql("n");
    let human_end = FixtureShape::HUMAN_LANE_ROWS;
    let lane_case = &format!("CASE WHEN n <= {human_end} THEN 'human' ELSE 'miss' END");
    let first_at = "datetime('now', '-' || (n % 2880) || ' minutes')";
    let not_before = "CASE WHEN n % 20 = 1 THEN datetime('now', '+30 minutes') \
                      ELSE '1970-01-01 00:00:00' END";
    let last_24h = FixtureShape::LAST_24H_ROWS;
    // Exactly `LAST_24H_ROWS` rows inside the outcome window; the rest
    // spread 1–28 days back so the window count never tracks queue size.
    let updated_at = &format!(
        "CASE WHEN n <= {last_24h} THEN datetime('now', '-' || (n % 1440) || ' minutes') \
              ELSE datetime('now', '-' || (1440 + n % 38880) || ' minutes') END"
    );
    let task_id = "printf('%064x', n)";
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}) \
         INSERT INTO queue (task_id, crate_name, version, features_json, target, rustc_version, \
                            downloads, miss_count, request_count, priority, status, lane, \
                            dispatch_attempts, not_before, first_requested_at, created_at, \
                            updated_at, host_side, preserve_lockfile, attempt, shape_requeue, \
                            github_run_id, deps_met, wake_at, dispatch_family, dispatch_key) \
         SELECT {task_id}, \
                'crate' || (n % 20000), \
                '1.0.' || (n % 500), \
                '[]', \
                {target_case}, \
                CASE WHEN n % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                n % 5000, 1, 1, n % 7, \
                CASE WHEN n <= {pending_end} THEN 'pending' \
                     WHEN n <= {completed_end} THEN 'completed' \
                     WHEN n <= {failed_end} THEN 'failed' \
                     WHEN n <= {in_flight_end} THEN CASE WHEN n % 2 = 0 THEN 'dispatched' \
                          ELSE 'running' END \
                     ELSE 'failed' END, \
                {lane_case}, \
                0, \
                {not_before}, \
                {first_at}, \
                {first_at}, \
                {updated_at}, \
                CASE WHEN n % 10 = 0 THEN 1 ELSE 0 END, \
                0, 1, CASE WHEN n > {pending_end} AND n <= {completed_end} THEN 1 ELSE 0 END, \
                CASE WHEN n > {in_flight_end} THEN 'run-' || n ELSE NULL END, \
                0, {wake}, {family}, {key} \
         FROM seq",
        seq = seq_sql(lo, hi),
        wake = crate::scheduler::queue::wake_at_sql(
            &format!("({lane_case})"),
            first_at,
            &format!("({not_before})"),
            min_age_minutes,
        ),
        family = crate::scheduler::queue::dispatch_family_sql(&format!("({target_case})")),
        key = crate::scheduler::queue::dispatch_key_sql(
            lane_case,
            &format!("({target_case})"),
            first_at,
            "(n % 7)",
            first_at,
            task_id,
        ),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed queue rows: {error}"))?;
    Ok(())
}

/// Seed the `phase`'s dependency edges for owner rows `(lo, hi]` — the
/// dep's identity is the same formula the `queue` seed applied at the
/// dep's own `n`.
pub async fn seed_edges_chunk(
    db: &DurableDb,
    shape: FixtureShape,
    phase: SeedPhase,
    lo: u32,
    hi: u32,
) -> Result<(), QueueError> {
    let rows = shape.queue_rows;
    let human_end = FixtureShape::HUMAN_LANE_ROWS;
    let human_pin = human_end - FixtureShape::HUMAN_PROBE_ROWS;
    let completed_dep = shape.pending_end() + 1;
    let thirds_where = format!("WHERE n % 3 = 0 AND (n <= {human_pin} OR n > {human_end})");
    let (dep_expr, extra) = match phase {
        SeedPhase::EdgesEvery => (
            format!(
                "CASE WHEN n > {human_pin} AND n <= {human_end} \
                 THEN {completed_dep} + (n % 64) \
                 ELSE (n * 7919) % {rows} + 1 END"
            ),
            "",
        ),
        SeedPhase::EdgesThirds => (
            format!("(n * 15485863) % {rows} + 1"),
            thirds_where.as_str(),
        ),
        _ => return Err(QueueError::Sql("not an edge phase".to_owned())),
    };
    let dep_target_case = target_case_sql(&dep_expr);
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}) \
         INSERT OR IGNORE INTO queue_dependencies \
             (task_id, depends_on_task_id, dep_crate_name, dep_version, dep_features_json, \
              dep_target, dep_rustc_version, dep_host_side, dep_invocations, dep_shapes, \
              dep_side_known) \
         SELECT printf('%064x', n), \
                printf('%064x', {dep_expr}), \
                'crate' || ({dep_expr} % 20000), \
                '1.0.' || ({dep_expr} % 500), \
                '[]', \
                {dep_target_case}, \
                CASE WHEN {dep_expr} % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                0, 1, 1, 1 \
         FROM seq {extra}",
        seq = seq_sql(lo, hi),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed dependency edges: {error}"))?;
    Ok(())
}

/// Seed the published-slice membership of completed rows `(lo, hi]` —
/// the identity columns are the row's own `n` formula, so the chunk
/// reads nothing outside its range.
pub async fn seed_slice_chunk(db: &DurableDb, lo: u32, hi: u32) -> Result<(), QueueError> {
    let target_case = target_case_sql("n");
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}) \
         INSERT INTO published_slice_rows \
             (target, rustc_version, generation, crate_name, version, features_json, \
              unit_side, unit_invocation, unit_linked) \
         SELECT {target_case}, \
                CASE WHEN n % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                1, 'crate' || (n % 20000), '1.0.' || (n % 500), '[]', 0, 0, 1 \
         FROM seq",
        seq = seq_sql(lo, hi),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed published slice rows: {error}"))?;
    Ok(())
}

/// The `published_slices` headers — one row per `(target, rustc)` pair
/// the completed identities carry; runs once when the `Slices` phase
/// finishes.
pub async fn seed_slice_headers(db: &DurableDb) -> Result<(), QueueError> {
    db.query(
        "INSERT INTO published_slices (target, rustc_version, generation) \
         SELECT DISTINCT target, rustc_version, 1 FROM published_slice_rows",
    )
    .execute()
    .await
    .map_err(|error| format!("seed published slices: {error}"))?;
    Ok(())
}

/// Recompute `deps_met` on the pending rows `(lo, hi]` — the flag the
/// claim walk and the alarm's probes read, seeded once the edges and
/// the published membership both exist.
pub async fn seed_deps_met_chunk(db: &DurableDb, lo: u32, hi: u32) -> Result<(), QueueError> {
    db.query(&format!(
        "UPDATE queue SET deps_met = {expr}, blocked = {blocked} \
         WHERE task_id >= printf('%064x', {lo} + 1) \
           AND task_id <= printf('%064x', {hi}) \
           AND (deps_met != {expr} OR blocked != {blocked})",
        expr = crate::scheduler::queue::deps_met_sql("queue.task_id"),
        blocked = crate::scheduler::queue::blocked_sql("queue.task_id"),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed deps_met/blocked: {error}"))?;
    Ok(())
}

/// Seed one `(n, n + batch]` chunk of `phase` and return where the seed
/// resumes — the next phase (or `None` once `DepsMet` finishes).
pub async fn seed_batch(
    db: &DurableDb,
    shape: FixtureShape,
    phase: SeedPhase,
    n: u32,
    batch: u32,
    min_age_minutes: u32,
) -> Result<(SeedPhase, u32, bool), QueueError> {
    let hi = (n + batch).min(phase.range_end(shape));
    if hi > n {
        match phase {
            SeedPhase::Queue => seed_queue_chunk(db, shape, n, hi, min_age_minutes).await?,
            SeedPhase::EdgesEvery | SeedPhase::EdgesThirds => {
                seed_edges_chunk(db, shape, phase, n, hi).await?;
            }
            SeedPhase::Slices => {
                seed_slice_chunk(db, n.max(phase.range_start(shape)), hi).await?;
                if hi >= phase.range_end(shape) {
                    seed_slice_headers(db).await?;
                }
            }
            SeedPhase::DepsMet => seed_deps_met_chunk(db, n, hi).await?,
        }
    }
    if hi >= phase.range_end(shape) {
        phase.next().map_or_else(
            || Ok((phase, hi, true)),
            |next| Ok((next, next.range_start(shape), false)),
        )
    } else {
        Ok((phase, hi, false))
    }
}

/// Seed the whole fixture on the host path — the same chunks the
/// workerd probe writes, looped until the seed reports done.
///
/// # Errors
/// Returns `QueueError::Sql` if any seed statement fails.
#[cfg(test)]
pub async fn seed_production_shape(
    db: &DurableDb,
    shape: &FixtureShape,
    min_age_minutes: u32,
) -> Result<(), QueueError> {
    let mut phase = SeedPhase::Queue;
    let mut n = phase.range_start(*shape);
    loop {
        let (next_phase, next_n, done) =
            seed_batch(db, *shape, phase, n, SEED_BATCH_ROWS, min_age_minutes).await?;
        if done {
            return Ok(());
        }
        phase = next_phase;
        n = next_n;
    }
}
