//! Deterministic production-shaped scheduler database for the stow#433
//! cost gate: `queue` rows plus their dependency edges and the
//! published-slice membership the dependency gate joins, generated by
//! `INSERT … SELECT` over a recursive CTE so seeding a fresh database
//! takes seconds and every row is a pure function of its sequence
//! number. The same generator seeds both harnesses: the host-side gate
//! drives [`FixtureShape::GATE`] (10k rows — a fast pre-check inside
//! `cargo test`), and the workerd harness seeds
//! [`FixtureShape::PRODUCTION`] (100k rows) into the Durable Object for
//! the numbers that gate a merge.
//!
//! Shape, in queue-order `n`:
//! * `n <= pending_end` are `pending` — about 60% of the queue;
//! * the next ~35% are `completed`, ~2.5% `failed`, and exactly thirty
//!   `dispatched`/`running` rows — fewer than the default 45-slot
//!   dispatch limit so the alarm's claim walk actually runs;
//! * a fixed [`FixtureShape::HUMAN_LANE_ROWS`] ride the human lane,
//!   ~5% carry a future `not_before`, `first_requested_at` spreads over
//!   the trailing two days, and exactly
//!   [`FixtureShape::LAST_24H_ROWS`] sit `updated_at` inside the last
//!   24 h — the quantities a route may legitimately be bounded by, held
//!   constant across fixture sizes so the scale check sees only the
//!   stored bulk grow;
//! * every pending row gains one edge (two when `n % 3 == 0`) onto the
//!   row at `dep_n`, whose status decides the gate: completed deps sit in
//!   the published slice (met edge), anything else leaves the edge unmet
//!   and the owner blocked. Most pending rows are blocked — the
//!   production shape the alarm used to re-scan in full every pass.
//!
//! Under workerd a single request cannot write the whole fixture — one
//! 100k-row insert plus its triggers and index entries outlives a
//! Durable Object request — so every seeder takes an `n` range and the
//! probe drives them in [`SEED_BATCH_ROWS`] chunks, resuming from a
//! cursor row in `settings`. On the host
//! [`seed_production_shape`] simply loops the same chunks.

use skyzen_services::durable::DurableDb;
use stow_types::api::{CI_TARGET_TRIPLES, SchedulerSeedReport, SchedulerSeedRequest};
pub use stow_types::fixture::FixtureShape;
use stow_types::fixture::{REQUEST_FIXTURE_ENQUEUED, REQUEST_FIXTURE_FAILED};

use crate::errors::QueueError;

/// The host-gate shape — 10k rows — small enough that `cargo test`
/// stays fast. Only the host pre-check uses it; the workerd harness
/// seeds `PRODUCTION` and the 1M shape `STOW_BUDGET_SIZES` carries.
#[cfg(test)]
pub const GATE: FixtureShape = FixtureShape { queue_rows: 10_000 };

/// Rows one crate name covers — the fixture's pinned per-name bound.
/// `'crate' || (n / CRATE_NAME_ROWS)` bounds every name to at most
/// `CRATE_NAME_ROWS` rows at any `queue_rows` — `n` starts at 1, so
/// `crate0` and the final bucket can be short — so a `crate_name =`
/// probe (`GET /tasks?crate=` sizes its budget by it) reads a
/// size-invariant cardinality at 10k, 100k and 1M instead of growing
/// with the table.
pub const CRATE_NAME_ROWS: u32 = 50;

/// How the fixture's `n % len` target spread maps onto
/// [`CI_TARGET_TRIPLES`].
fn target_count() -> u32 {
    u32::try_from(CI_TARGET_TRIPLES.len()).expect("target count fits u32")
}

/// `CASE` arms assigning `expr` a target triple — generated from
/// [`CI_TARGET_TRIPLES`] so the fixture's spread follows the real list.
/// `expr` is `n` for the owner row and the dep-picker expression for an
/// edge row.
fn target_case_sql(expr: &str) -> String {
    use std::fmt::Write as _;
    let mut arms = String::new();
    for (index, target) in CI_TARGET_TRIPLES.iter().enumerate() {
        let _ = write!(arms, "WHEN {index} THEN '{target}' ");
    }
    format!("CASE ({expr}) % {} {arms}END", target_count())
}

/// `dep_invocation_mask(triple, false)` per CI target, evaluated in
/// Rust so the CASE constants are production's own rule — the
/// target-side arm of `dep_edge_requirements` and the non-host side of
/// the owner's mask. (The host-owner arm is the literal `3` the
/// callers add: a host-side task's mask is not a function of its
/// target.)
fn target_mask_case(expr: &str) -> String {
    use std::fmt::Write as _;
    let mut arms = String::new();
    for (index, target) in CI_TARGET_TRIPLES.iter().enumerate() {
        let _ = write!(
            arms,
            "WHEN {index} THEN {} ",
            crate::scheduler::queue::dep_invocation_mask(target, false)
        );
    }
    format!("CASE ({expr}) % {} {arms}END", target_count())
}

/// The invocation spelling a target-side node's own build runs —
/// `UnitInvocation::for_task` on the node's target against its
/// family's host triple — as a per-target CASE, matching the
/// invocation `required_unit_shapes` takes.
fn target_invocation_case(expr: &str) -> String {
    use std::fmt::Write as _;
    let mut arms = String::new();
    for (index, target) in CI_TARGET_TRIPLES.iter().enumerate() {
        let invocation = stow_types::api::runner_family(target).map_or(
            stow_types::public_cache::UnitInvocation::Native,
            |family| {
                stow_types::public_cache::UnitInvocation::for_task(target, family.host_triple())
            },
        );
        let _ = write!(arms, "WHEN {index} THEN {} ", invocation.to_int());
    }
    format!("CASE ({expr}) % {} {arms}END", target_count())
}

/// Rows one seeder call covers — bounded so a probe request never holds
/// a statement (or a request's worth of trigger and index writes) large
/// enough to outlive the Durable Object runtime.
pub const SEED_BATCH_ROWS: u32 = 4_000;

/// One of the three fixture tables the seed report counts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CountedTable {
    /// `queue`.
    Queue,
    /// `queue_dependencies`.
    Dependencies,
    /// `published_slice_rows`.
    Slices,
}

impl CountedTable {
    /// The table a counter names, by its SQL name — `None` for a table
    /// the seed does not count (`requests`, `published_slices`).
    pub fn for_table(table: &str) -> Option<Self> {
        match table {
            "queue" => Some(Self::Queue),
            "queue_dependencies" => Some(Self::Dependencies),
            "published_slice_rows" => Some(Self::Slices),
            _ => None,
        }
    }
}

/// Rows the seed's three counted fixture tables hold — the totals the
/// `/budget/seed` report answers. They ride inside the seed cursor's
/// `settings` row so a chunk's advance and its tallies commit as one
/// statement: the write either lands whole or not at all, so a reply
/// lost after the commit cannot split the progress record, and a
/// replay of the call re-derives the same counters from the same
/// cursor. They are never re-derived from `COUNT(*)` per request — a
/// per-call count re-read a table that grows with the fixture, the
/// linear cost the chunked seed exists to bound.
///
/// The counters' authority differs per table, matching how the chunk
/// writes are shaped: `queue`/`slices` chunk inserts are atomic
/// `INSERT … SELECT` over a known row range, so the counter is SET to
/// the cursor position (the position is the count — a statement
/// either inserted the whole chunk or errored). `queue_dependencies`
/// inserts are `OR IGNORE` — a dep already present is skipped — so
/// its counter accumulates `SELECT changes()`, which SQLite defines
/// as the statement's direct row changes, never index or trigger
/// writes (the billed `rows_written` the backend reports counts
/// those, and cannot name records).
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct SeedCounts {
    /// Rows `queue` holds.
    pub queue: u64,
    /// Rows `queue_dependencies` holds.
    pub dependencies: u64,
    /// Rows `published_slice_rows` holds.
    pub slices: u64,
}

impl SeedCounts {
    /// The cursor's counts field — `"<queue>,<deps>,<slices>"`.
    pub fn encode(self) -> String {
        format!("{},{},{}", self.queue, self.dependencies, self.slices)
    }

    /// The counts field of a cursor — `Err` on anything but three
    /// `u64`s; the cursor is internal operator state, so a malformed
    /// field is corruption, not a compatibility case.
    pub fn decode(field: &str) -> Result<Self, QueueError> {
        let bad = || QueueError::Sql(format!("bad seed cursor counts {field:?}"));
        let mut parts = field.split(',');
        let mut number = || {
            parts
                .next()
                .ok_or_else(bad)?
                .parse::<u64>()
                .map_err(|_| bad())
        };
        let counts = Self {
            queue: number()?,
            dependencies: number()?,
            slices: number()?,
        };
        if parts.next().is_some() {
            return Err(bad());
        }
        Ok(counts)
    }

    /// `table`'s current counter.
    pub const fn get(&self, table: CountedTable) -> u64 {
        match table {
            CountedTable::Queue => self.queue,
            CountedTable::Dependencies => self.dependencies,
            CountedTable::Slices => self.slices,
        }
    }

    /// Set `table`'s counter — the position-derived totals.
    pub const fn set(&mut self, table: CountedTable, n: u64) {
        match table {
            CountedTable::Queue => self.queue = n,
            CountedTable::Dependencies => self.dependencies = n,
            CountedTable::Slices => self.slices = n,
        }
    }

    /// Add `n` inserted records to `table` — exact arithmetic: a
    /// counter that could overflow or go negative means the progress
    /// record is already wrong, which is a bug to surface, not a
    /// bound to clamp.
    pub fn add(&mut self, table: CountedTable, n: u64) -> Result<(), QueueError> {
        let next = self
            .get(table)
            .checked_add(n)
            .ok_or_else(|| QueueError::Sql("seed counter overflow".to_owned()))?;
        self.set(table, next);
        Ok(())
    }

    /// Subtract `n` deleted records — the wipe chunk's telemetry, exact
    /// like `add`.
    pub fn subtract(&mut self, table: CountedTable, n: u64) -> Result<(), QueueError> {
        let next = self
            .get(table)
            .checked_sub(n)
            .ok_or_else(|| QueueError::Sql("seed counter underflow".to_owned()))?;
        self.set(table, next);
        Ok(())
    }
}

/// Which stretch of the fixture a seeder call writes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeedPhase {
    /// `queue` rows — `n` runs `1..=queue_rows`.
    Queue,
    /// The every-owner edge (`dep_n = n * 7919`) — `n` runs
    /// `1..=pending_end`.
    EdgesEvery,
    /// The every-third-owner edge (`dep_n = n * 15485863`) — `n` runs
    /// `1..=pending_end`.
    EdgesThirds,
    /// `task_nodes` for every queue row — `n` runs `1..=queue_rows`.
    /// Runs after the edge phases so `children_json` can read the
    /// seeded `queue_dependencies`.
    Nodes,
    /// `published_slice_rows` for the completed identities — `n` runs
    /// `pending_end < n <= completed_end`. The caller inserts the
    /// `published_slices` header rows once this phase completes.
    Slices,
    /// The `deps_met` recompute — `n` runs `1..=pending_end`.
    DepsMet,
    /// The feed bulk's retained delivered headers — `n` runs
    /// `1..=feed_hist_hours` (stow#523).
    FeedHeaders,
    /// The feed bulk's retained delivered pages — `n` runs
    /// `1..=feed_hist_pages`.
    FeedPages,
    /// The staging hour's current-generation bulk plus its 256-row
    /// obsolete tail — `n` runs `1..=feed_staged_pages + 256`.
    FeedStaged,
}

impl SeedPhase {
    /// The phase's `n` ceiling; `next` is where the cursor goes when `n`
    /// reaches it. `pub` for the budget route's position-derived
    /// counters (an ended phase reports its range end).
    pub fn range_end(self, shape: FixtureShape) -> u32 {
        match self {
            Self::Queue | Self::Nodes => shape.queue_rows,
            Self::EdgesEvery | Self::EdgesThirds | Self::DepsMet => shape.pending_end(),
            Self::Slices => shape.completed_end(),
            Self::FeedHeaders => feed_hist_hours(shape),
            Self::FeedPages => feed_hist_pages(shape),
            Self::FeedStaged => feed_staged_pages(shape) + FEED_OBSOLETE_TAIL,
        }
    }

    /// The `n` a phase resumes from.
    const fn range_start(self, shape: FixtureShape) -> u32 {
        match self {
            Self::Slices => shape.pending_end(),
            _ => 0,
        }
    }

    /// The phase the cursor advances to when this one finishes; `None`
    /// ends the seed.
    const fn next(self) -> Option<Self> {
        match self {
            Self::Queue => Some(Self::EdgesEvery),
            Self::EdgesEvery => Some(Self::EdgesThirds),
            Self::EdgesThirds => Some(Self::Nodes),
            Self::Nodes => Some(Self::Slices),
            Self::Slices => Some(Self::DepsMet),
            Self::DepsMet => Some(Self::FeedHeaders),
            Self::FeedHeaders => Some(Self::FeedPages),
            Self::FeedPages => Some(Self::FeedStaged),
            Self::FeedStaged => None,
        }
    }
}

/// The `n` domain `WITH RECURSIVE seq` generates — a chunk is always a
/// contiguous `(lo, hi]` slice of a phase's range, so the statement
/// materializes only its own rows.
fn seq_sql(lo: u32, hi: u32) -> String {
    format!("SELECT {lo} + 1 UNION ALL SELECT n + 1 FROM seq WHERE n < {hi}")
}

/// The `queue` columns the seed writes, in statement order — shared
/// between the chunk INSERT and the re-arm upsert so both address the
/// same list (`task_id` is the conflict key, never an update target).
const QUEUE_SEED_COLUMNS: &[&str] = &[
    "task_id",
    "crate_name",
    "version",
    "features_json",
    "target",
    "rustc_version",
    "downloads",
    "miss_count",
    "request_count",
    "priority",
    "status",
    "lane",
    "dispatch_attempts",
    "not_before",
    "first_requested_at",
    "created_at",
    "updated_at",
    "host_side",
    "preserve_lockfile",
    "attempt",
    "shape_requeue",
    "github_run_id",
    "generation_id",
    "unpublished_deps",
    "deps_met",
    "wake_at",
    "dispatch_family",
    "value",
    "dispatch_key",
    "claimed_at",
    "dispatch_eligible",
    "demand",
];

/// Build the seed's queue statement over an arbitrary `seq` source:
/// identity and scheduling columns are functions of `n`, including the `dispatch_key`
/// the claim walk orders on and the `wake_at` the alarm probes read
/// (computed under the same `dispatch_min_age_minutes` the deploy runs).
/// `verb` distinguishes the idempotent seed (`INSERT OR IGNORE`) from
/// the restore (`INSERT`), and `conflict` carries the upsert clause —
/// empty for the seed.
/// Dispatch generations are fresh 128-bit identities on each insert or
/// restore; they identify an execution, independently of the stable task.
///
/// `(crate, version)` is injective in `n` — `n / 20000` carries the
/// quotient in the version and `n % 500` its low digits — so the
/// queue's UNIQUE identity holds at any `queue_rows`; under 20000 rows
/// the version still reads `1.0.x`, the shape the drives and the
/// 20k/100k runs were written against. The name groups a bounded
/// version set: `n / CRATE_NAME_ROWS` bounds every `crate_name` to at
/// most `CRATE_NAME_ROWS` rows at any size (see the constant).
fn queue_seed_insert_sql(
    shape: FixtureShape,
    seq_source: &str,
    min_age_minutes: u32,
    verb: &str,
    conflict: &str,
) -> String {
    let pending_end = shape.pending_end();
    let completed_end = shape.completed_end();
    let failed_end = shape.failed_end();
    let in_flight_end = failed_end + FixtureShape::IN_FLIGHT_ROWS;
    let target_case = target_case_sql("n");
    let human_end = FixtureShape::HUMAN_LANE_ROWS;
    let lane_case = &format!("CASE WHEN n <= {human_end} THEN 'human' ELSE 'miss' END");
    let first_at = "datetime('now', '-' || (n % 2880) || ' minutes')";
    let not_before = &format!(
        "CASE WHEN (n <= {failed_end} OR n > {in_flight_end}) AND n % 20 = 1 \
         THEN datetime('now', '+30 minutes') \
         ELSE '1970-01-01 00:00:00' END"
    );
    let last_24h = FixtureShape::LAST_24H_ROWS;
    // In-flight rows model attempts with a live heartbeat: stamped ahead
    // of any lease horizon so the stale-dispatch recovery never reclaims
    // them, however long the drive runs — a fixed past offset ages out
    // mid-drive and the reclaim flips them out from under the lanes and
    // probes that measure on them. A future stamp is still a normal
    // `updated_at` write to everything else that reads it.
    // Exactly `LAST_24H_ROWS` rows inside the outcome window; the rest
    // spread 1–28 days back so the window count never tracks queue size.
    let updated_at = &format!(
        "CASE WHEN n > {failed_end} AND n <= {in_flight_end} \
              THEN datetime('now', '+1 day') \
              WHEN n <= {last_24h} THEN datetime('now', '-' || (n % 1440) || ' minutes') \
              ELSE datetime('now', '-' || (1440 + n % 38880) || ' minutes') END"
    );
    let task_id = "printf('%064x', n)";
    let bands_expr = format!(
        "(CASE WHEN ({lane_case}) = 'human' THEN 2 ELSE 0 END) + \
         (CASE WHEN ({family}) = 'windows' THEN 1 ELSE 0 END)",
        family = crate::scheduler::queue::dispatch_family_sql(&format!("({target_case})")),
    );
    let key = format!(
        "({prefix}) || '|' || ({first_at}) || '|' || ({first_at}) || '|' || ({task_id})",
        prefix = rank_prefix_case_sql(&bands_expr),
    );
    format!(
        "WITH RECURSIVE seq(n) AS ({seq_source}) \
         {verb} INTO queue ({columns}) \
         SELECT {task_id}, \
                'crate' || (n / {CRATE_NAME_ROWS}), \
                '1.' || (n / 20000) || '.' || (n % 500), \
                '[]', \
                {target_case}, \
                CASE WHEN n % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                n % 5000, 1, 1, n % 7, \
                CASE WHEN n <= {pending_end} THEN 'pending' \
                     WHEN n <= {completed_end} THEN 'completed' \
                     WHEN n <= {failed_end} THEN 'failed' \
                     WHEN n <= {in_flight_end} THEN CASE WHEN n % 2 = 0 THEN 'dispatched' \
                          ELSE 'running' END \
                     ELSE 'failed' END, \
                {lane_case}, \
                CASE WHEN n > {failed_end} AND n <= {in_flight_end} THEN 1 ELSE 0 END, \
                {not_before}, \
                {first_at}, \
                {first_at}, \
                {updated_at}, \
                CASE WHEN n % 10 = 0 THEN 1 ELSE 0 END, \
                0, 1, CASE WHEN n > {pending_end} AND n <= {completed_end} THEN 1 ELSE 0 END, \
                CASE WHEN n > {failed_end} THEN 'run-' || n ELSE NULL END, \
                lower(hex(randomblob(16))), \
                0, 0, {wake}, {family}, {value}, {key}, \
                CASE WHEN n > {failed_end} AND n <= {in_flight_end} \
                     THEN datetime('now', '-30 minutes') ELSE NULL END, \
                {eligible}, 0 \
         FROM seq \
         {conflict}",
        columns = QUEUE_SEED_COLUMNS.join(", "),
        wake = crate::scheduler::queue::wake_at_sql(
            &format!("({lane_case})"),
            first_at,
            &format!("({not_before})"),
            min_age_minutes,
        ),
        family = crate::scheduler::queue::dispatch_family_sql(&format!("({target_case})")),
        value = crate::scheduler::queue::value_sql(
            &format!("({lane_case})"),
            &crate::scheduler::queue::dispatch_family_sql(&format!("({target_case})")),
            "(n % 7)",
            "0",
        ),
        key = key,
        eligible = crate::scheduler::queue::dispatch_eligible_sql(
            &format!("({lane_case})"),
            &crate::scheduler::queue::value_sql(
                &format!("({lane_case})"),
                &crate::scheduler::queue::dispatch_family_sql(&format!("({target_case})")),
                "(n % 7)",
                "0",
            ),
        ),
    )
}

/// The `dispatch_key` rank prefix for the seed's small constant
/// operand set — lane/family bands (0–3) crossed with the `n % 7`
/// priority — each arm carrying the shared Rust abstraction's fixed
/// prefix at the unmeasured cost 1, so a fixture row's key is
/// byte-identical to what a writer derives for the same operands. The
/// ranking formula itself never appears in SQL; the CASE only
/// selects among the precomputed prefixes, and an operand outside the
/// covered set yields NULL — a loud seed failure, not a silent key.
fn rank_prefix_case_sql(bands_expr: &str) -> String {
    use std::fmt::Write as _;
    let mut case = format!("CASE ({bands_expr}) * 7 + (n % 7)");
    for band in 0_i64..4 {
        for priority in 0_i64..7 {
            let lane = if band >= 2 { "human" } else { "miss" };
            let value = band * crate::scheduler::queue::VALUE_BAND + priority;
            let prefix = crate::scheduler::rank::rank_prefix(
                lane,
                value,
                crate::scheduler::rank::UNMEASURED_COST,
            );
            let _ = write!(case, " WHEN {} THEN '{prefix}'", band * 7 + priority);
        }
    }
    format!("{case} END")
}

/// Seed `queue` rows `(lo, hi]`.
pub async fn seed_queue_chunk(
    db: &DurableDb,
    shape: FixtureShape,
    lo: u32,
    hi: u32,
    min_age_minutes: u32,
) -> Result<(), QueueError> {
    // `OR IGNORE` — not for collisions (the identities are injective)
    // but so a replay of a chunk whose cursor commit was lost re-runs
    // idempotently instead of stalling on its own identity keys.
    db.query(&queue_seed_insert_sql(
        shape,
        &seq_sql(lo, hi),
        min_age_minutes,
        "INSERT OR IGNORE",
        "",
    ))
    .execute()
    .await
    .map_err(|error| format!("seed queue rows: {error}"))?;
    Ok(())
}

/// Re-seed the exact rows `ns` name — the budget re-arm's restore for
/// the seeded rows the drives mutate or delete: each listed `n` is
/// written with the seed's own column formulas, so a retried, purged,
/// resynced or completed row returns to the state the probe was
/// calibrated on. `seq` is fed from `json_each`, not a range — only
/// the named rows are touched. The upsert (not `INSERT OR REPLACE`,
/// whose implied DELETE would mis-fire the status counters' triggers)
/// restores every seeded column; the two columns the seed leaves to
/// defaults (`error_msg`, `blocked`) reset explicitly. The gate counter
/// fields land at their seed values here and the caller recomputes them
/// once the edges and slices the flags read are restored too.
pub async fn restore_queue_rows(
    db: &DurableDb,
    shape: FixtureShape,
    min_age_minutes: u32,
    ns: &[u32],
) -> Result<(), QueueError> {
    if ns.is_empty() {
        return Ok(());
    }
    let assignments = QUEUE_SEED_COLUMNS
        .iter()
        .filter(|column| **column != "task_id")
        .map(|column| format!("{column} = excluded.{column}"))
        .collect::<Vec<_>>()
        .join(", ");
    let sql = queue_seed_insert_sql(
        shape,
        "SELECT CAST(value AS INTEGER) FROM json_each(?)",
        min_age_minutes,
        "INSERT",
        // `WHERE 1` ends the SELECT's join grammar — without it `ON
        // CONFLICT` parses as a join constraint and `DO` is a syntax
        // error (SQLite's documented upsert ambiguity).
        &format!(
            "WHERE 1 ON CONFLICT(task_id) DO UPDATE SET {assignments}, \
             error_msg = NULL, blocked = 0"
        ),
    );
    db.query(&sql)
        .bind(
            serde_json::to_string(ns)
                .map_err(|error| QueueError::Sql(format!("encode restore row ids: {error}")))?,
        )
        .execute()
        .await
        .map_err(|error| format!("restore seeded queue rows: {error}"))?;
    Ok(())
}

/// Seed the `phase`'s dependency edges for owner rows `(lo, hi]` — the
/// dep's identity is the same formula the `queue` seed applied at the
/// dep's own `n`.
pub async fn seed_edges_chunk(
    db: &DurableDb,
    shape: FixtureShape,
    phase: SeedPhase,
    lo: u32,
    hi: u32,
) -> Result<u64, QueueError> {
    let rows = shape.queue_rows;
    let human_end = FixtureShape::HUMAN_LANE_ROWS;
    let human_pin = human_end - FixtureShape::HUMAN_PROBE_ROWS;
    let completed_dep = shape.pending_end() + 1;
    let completed_end = shape.completed_end();
    let thirds_where = format!("WHERE n % 3 = 0 AND (n <= {human_pin} OR n > {human_end})");
    // `completed_dep` is the fixture's pinned dep leaf (stow#588): the
    // claim's `deps_met = 1` gate admits only rows whose every edge is
    // met — met means the dep row is published — so claimable rows'
    // children point at the completed range. Arms that must produce
    // claimable rows (the human-lane pin and every fourth pending row)
    // all point at the SAME leaf, and any size-scaled random pick that
    // would land in the completed range is rerouted to that leaf too —
    // otherwise a met edge could name a different completed row at each
    // size and the closure's node count would drift with the pick. The
    // claimed set's node-store closure is then `{claimed, completed_dep}`
    // — depth 1, claims+1 nodes — identical at every fixture size, the
    // way the in-flight count and the slice delta are already pinned.
    // Random picks that land on pending or in-flight rows stay put,
    // which is what keeps most pending rows blocked on unmet deps.
    let (dep_expr, extra) = match phase {
        SeedPhase::EdgesEvery => (
            format!(
                "CASE WHEN n > {human_pin} AND n <= {human_end} THEN {completed_dep} \
                      WHEN n % 4 = 0 THEN {completed_dep} \
                      WHEN ((n * 7919) % {rows} + 1) >= {completed_dep} \
                           AND ((n * 7919) % {rows} + 1) <= {completed_end} \
                           THEN {completed_dep} \
                      ELSE (n * 7919) % {rows} + 1 END"
            ),
            "",
        ),
        SeedPhase::EdgesThirds => (
            format!(
                "CASE WHEN n % 4 = 0 THEN {completed_dep} \
                      WHEN ((n * 15485863) % {rows} + 1) >= {completed_dep} \
                           AND ((n * 15485863) % {rows} + 1) <= {completed_end} \
                           THEN {completed_dep} \
                      ELSE (n * 15485863) % {rows} + 1 END"
            ),
            thirds_where.as_str(),
        ),
        _ => return Err(QueueError::Sql("not an edge phase".to_owned())),
    };
    // `dep` is the dep row's `n` as one parenthesized unit — spliced
    // next to an operator it must evaluate as a whole, or the outer
    // operator binds into the expression's last term (`%` and `/`
    // bind tighter than `+`, so an arm like `X % rows + 1` would
    // otherwise evaluate the outer operator against `1` first).
    let dep = format!("({dep_expr})");
    let dep_target_case = target_case_sql(&dep);
    // The edge's side and requirement columns are the same inputs
    // production's `dep_edge_requirements` reads, evaluated as CASEs:
    // `dep_host_side` is the dep row's own side (`n % 10 = 0` is the
    // fixture's host arm); a host-side dep needs the owner's
    // invocation mask and its popcount (a host owner's mask covers
    // both spellings — 3, popcount 2 — a target owner's one spelling,
    // popcount 1); a target-side dep needs its own target's mask and
    // its two linked/unlinked shapes. No production edge carries the
    // old `(0, 1, 1)` literals.
    let owner_mask = format!(
        "CASE WHEN n % 10 = 0 THEN 3 ELSE {} END",
        target_mask_case("n")
    );
    let dep_mask = target_mask_case(&dep);
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}) \
         INSERT OR IGNORE INTO queue_dependencies \
             (task_id, depends_on_task_id, dep_crate_name, dep_version, dep_features_json, \
              dep_target, dep_rustc_version, dep_host_side, dep_dependency_identity, \
              dep_invocations, dep_shapes, dep_side_known) \
         SELECT printf('%064x', n), \
                printf('%064x', {dep}), \
                'crate' || ({dep} / {CRATE_NAME_ROWS}), \
                '1.' || ({dep} / 20000) || '.' || ({dep} % 500), \
                '[]', \
                {dep_target_case}, \
                CASE WHEN {dep} % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                CASE WHEN {dep} % 10 = 0 THEN 1 ELSE 0 END, \
                printf('%064x', {dep}), \
                CASE WHEN {dep} % 10 = 0 THEN ({owner_mask}) ELSE ({dep_mask}) END, \
                CASE WHEN {dep} % 10 = 0 THEN CASE WHEN n % 10 = 0 THEN 2 ELSE 1 END ELSE 2 END, \
                1 \
         FROM seq {extra}",
        seq = seq_sql(lo, hi),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed dependency edges: {error}"))?;
    // The `OR IGNORE` makes the actual insert count a measured value,
    // not `(hi - lo)` — deps an earlier owner already wrote are
    // skipped.
    crate::scheduler::queue::changes(db).await
}

/// Seed `task_nodes` for queue rows `(lo, hi]` (stow#588): each row's
/// node carries the same identity columns as its `queue` row, its own
/// task id as the `dependency_identity` (the fixture's synthetic digest —
/// edges and slice rows agree by the same formula), and a
/// `children_json` built from the seeded `queue_dependencies`, so the
/// dispatch walk can expand every claimable row's subgraph.
async fn seed_nodes_chunk(db: &DurableDb, lo: u32, hi: u32) -> Result<(), QueueError> {
    let target_case = target_case_sql("n");
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}) \
         INSERT OR IGNORE INTO task_nodes \
             (task_id, crate_name, version, features_json, target, rustc_version, \
              host_side, dependency_identity, children_json) \
         SELECT printf('%064x', n), \
                'crate' || (n / {CRATE_NAME_ROWS}), \
                '1.' || (n / 20000) || '.' || (n % 500), \
                '[]', \
                {target_case}, \
                CASE WHEN n % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                CASE WHEN n % 10 = 0 THEN 1 ELSE 0 END, \
                printf('%064x', n), \
                COALESCE( \
                    (SELECT json_group_array(d.depends_on_task_id) \
                     FROM queue_dependencies d \
                     WHERE d.task_id = printf('%064x', n)), \
                    '[]') \
         FROM seq",
        seq = seq_sql(lo, hi),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed task nodes: {error}"))?;
    Ok(())
}

/// Seed the published-slice membership of completed rows `(lo, hi]` —
/// two rows per node, the pair `required_unit_shapes` publishes for
/// it: a host-side node (`n % 10 = 0`, the fixture's host arm)
/// carries the linked unit under both invocation spellings, and a
/// target-side node carries the unlinked and linked units at its own
/// invocation — the spelling `UnitInvocation::for_task` assigns its
/// target on the family's host. The `part` join enumerates the pair.
pub async fn seed_slice_chunk(db: &DurableDb, lo: u32, hi: u32) -> Result<(), QueueError> {
    let target_case = target_case_sql("n");
    let node_invocation = target_invocation_case("n");
    db.query(&format!(
        "WITH RECURSIVE seq(n) AS ({seq}), \
         rows(target, rustc_version, generation, crate_name, version, features_json, \
              dependency_identity, unit_side, unit_invocation, unit_linked) AS ( \
            SELECT {target_case}, \
                   CASE WHEN n % 3 < 2 THEN '1.85.0' ELSE '1.86.0' END, \
                   1, 'crate' || (n / {CRATE_NAME_ROWS}), '1.' || (n / 20000) || '.' || (n % 500), '[]', \
                   printf('%064x', n), \
                   CASE WHEN n % 10 = 0 THEN 1 ELSE 0 END, \
                   CASE WHEN n % 10 = 0 THEN part ELSE {node_invocation} END, \
                   CASE WHEN n % 10 = 0 THEN 1 ELSE part END \
            FROM seq, (SELECT 0 AS part UNION ALL SELECT 1 AS part)) \
         INSERT OR IGNORE INTO published_slice_rows \
             (target, rustc_version, generation, crate_name, version, features_json, \
              dependency_identity, unit_side, unit_invocation, unit_linked) \
         SELECT target, rustc_version, generation, crate_name, version, features_json, \
                dependency_identity, unit_side, unit_invocation, unit_linked \
         FROM rows \
         WHERE NOT EXISTS ( \
            SELECT 1 FROM published_slice_rows p \
            WHERE p.target = rows.target AND p.rustc_version = rows.rustc_version \
              AND p.generation = rows.generation AND p.crate_name = rows.crate_name \
              AND p.version = rows.version AND p.features_json = rows.features_json \
              AND p.dependency_identity = rows.dependency_identity \
              AND p.unit_side = rows.unit_side AND p.unit_invocation = rows.unit_invocation \
              AND p.unit_linked = rows.unit_linked)",
        seq = seq_sql(lo, hi),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed published slice rows: {error}"))?;
    Ok(())
}

/// The `published_slices` headers — one row per `(target, rustc)` pair
/// the completed identities carry; runs once when the `Slices` phase
/// finishes.
pub async fn seed_slice_headers(db: &DurableDb) -> Result<(), QueueError> {
    db.query(
        "INSERT OR IGNORE INTO published_slices (target, rustc_version, generation) \
         SELECT DISTINCT target, rustc_version, 1 FROM published_slice_rows",
    )
    .execute()
    .await
    .map_err(|error| format!("seed published slices: {error}"))?;
    Ok(())
}

/// Recompute the persisted gate answers on the pending rows `(lo, hi]`
/// — the flags the claim walk and the alarm's probes read, seeded once
/// the edges and the published membership both exist. The edges'
/// `dep_met` goes first: the owner counters count those flags.
pub async fn seed_deps_met_chunk(db: &DurableDb, lo: u32, hi: u32) -> Result<(), QueueError> {
    db.query(&format!(
        "UPDATE queue_dependencies SET dep_met = CASE WHEN {unpub} THEN 0 ELSE 1 END \
         WHERE task_id >= printf('%064x', {lo} + 1) \
           AND task_id <= printf('%064x', {hi}) \
           AND dep_met != (CASE WHEN {unpub} THEN 0 ELSE 1 END)",
        unpub = crate::scheduler::queue::dep_edge_unpublished_sql("queue_dependencies"),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed edge dep_met: {error}"))?;
    db.query(&format!(
        "UPDATE queue SET unpublished_deps = {unpublished}, deps_met = {expr}, blocked = {blocked} \
         WHERE task_id >= printf('%064x', {lo} + 1) \
           AND task_id <= printf('%064x', {hi}) \
           AND (unpublished_deps != {unpublished} OR deps_met != {expr} OR blocked != {blocked})",
        unpublished = crate::scheduler::queue::unpublished_deps_sql("queue.task_id"),
        expr = crate::scheduler::queue::deps_met_sql("queue.task_id"),
        blocked = crate::scheduler::queue::blocked_sql("queue.task_id"),
    ))
    .execute()
    .await
    .map_err(|error| format!("seed deps_met/blocked: {error}"))?;
    Ok(())
}

/// Restore persisted gate answers for the exact rows a probe touched:
/// edge flags first, then each owner's counter and status flags. The owner
/// set is the explicit control/claimed rows plus their direct dependents;
/// it never ranges over the stored queue or edge bulk.
async fn refresh_rearm_gate_state(db: &DurableDb, touched: &[u32]) -> Result<(), QueueError> {
    if touched.is_empty() {
        return Ok(());
    }
    let touched_json = serde_json::to_string(touched)
        .map_err(|error| QueueError::Sql(format!("encode re-arm ids: {error}")))?;
    let owners = "WITH touched(task_id) AS ( \
                      SELECT printf('%064x', value) FROM json_each(?) \
                  ), owners(task_id) AS ( \
                      SELECT task_id FROM touched \
                      UNION \
                      SELECT d.task_id \
                      FROM queue_dependencies d \
                      JOIN touched t ON t.task_id = d.depends_on_task_id \
                  )";
    db.query(&format!(
        "{owners} UPDATE queue_dependencies \
         SET dep_met = CASE WHEN {unpublished} THEN 0 ELSE 1 END \
         WHERE task_id IN (SELECT task_id FROM owners) \
           AND dep_met != (CASE WHEN {unpublished} THEN 0 ELSE 1 END)",
        unpublished = crate::scheduler::queue::dep_edge_unpublished_sql("queue_dependencies"),
    ))
    .bind(touched_json.clone())
    .execute()
    .await
    .map_err(|error| format!("re-arm edge dep_met: {error}"))?;
    db.query(&format!(
        "{owners} UPDATE queue \
         SET unpublished_deps = {unpublished}, \
             deps_met = {deps_met}, \
             blocked = CASE WHEN queue.status = 'pending' THEN {blocked} \
                            ELSE queue.blocked END \
         WHERE queue.task_id IN (SELECT task_id FROM owners) \
           AND (queue.unpublished_deps != {unpublished} \
                OR queue.deps_met != {deps_met} \
                OR (queue.status = 'pending' AND queue.blocked != {blocked}))",
        unpublished = crate::scheduler::queue::unpublished_deps_sql("queue.task_id"),
        deps_met = crate::scheduler::queue::deps_met_sql("queue.task_id"),
        blocked = crate::scheduler::queue::blocked_sql("queue.task_id"),
    ))
    .bind(touched_json)
    .execute()
    .await
    .map_err(|error| format!("re-arm gate counters: {error}"))?;
    Ok(())
}

/// The `settings` key the budget pass's claim record lives under — the
/// pass's own dispatch outcome written there after the metered window
/// closes, so the next run's [`rearm`] restores exactly the rows the
/// pass claimed, never a status- or band-scoped guess at them.
const PROBE_CLAIMED_KEY: &str = "budget_probe_claimed";

/// Persist the task ids a budget pass claimed — one `settings` upsert
/// outside the metered window, read and cleared by [`rearm`] on the
/// next run. An empty record is kept, not dropped: the previous run's
/// record must never survive a pass that claimed nothing.
pub async fn record_probe_claimed(db: &DurableDb, task_ids: &[String]) -> Result<(), QueueError> {
    db.query(
        "INSERT INTO settings (key, value) VALUES (?, ?) \
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    )
    .bind(PROBE_CLAIMED_KEY)
    .bind(
        serde_json::to_string(task_ids)
            .map_err(|error| QueueError::Sql(format!("encode probe claim record: {error}")))?,
    )
    .execute()
    .await
    .map_err(|error| QueueError::Sql(format!("record probe claims: {error}")))?;
    Ok(())
}

/// Read, clear, and re-seed the last pass's claim set — consumed on
/// read so a pass that claims nothing leaves nothing to restore. The
/// ids are the pass's own recorded outcome: only they are upserted
/// back to the seeded row, claim-written `attempt`/`wake_at`/
/// `not_before`/`dispatch_attempts` and all, never a status- or
/// band-scoped guess. Returns the seeded row numbers for the flag
/// recompute's `touched` set.
async fn restore_claimed_rows(
    db: &DurableDb,
    shape: FixtureShape,
    min_age_minutes: u32,
) -> Result<Vec<u32>, QueueError> {
    let claimed_ids: Option<Vec<String>> = db
        .query("SELECT value FROM settings WHERE key = ?")
        .bind(PROBE_CLAIMED_KEY)
        .fetch_scalar_optional::<String>()
        .await
        .map_err(|error| QueueError::Sql(format!("read probe claim record: {error}")))?
        .map(|json| {
            serde_json::from_str::<Vec<String>>(&json)
                .map_err(|error| QueueError::Sql(format!("parse probe claim record: {error}")))
        })
        .transpose()?;
    if claimed_ids.is_some() {
        db.query("DELETE FROM settings WHERE key = ?")
            .bind(PROBE_CLAIMED_KEY)
            .execute()
            .await
            .map_err(|error| QueueError::Sql(format!("clear probe claim record: {error}")))?;
    }
    let claimed_ns: Vec<u32> = claimed_ids
        .unwrap_or_default()
        .iter()
        .filter_map(|id| {
            // A claimed row a drive inserted is content-keyed — the
            // `%-%` cleanup already deleted it; only seeded (hex) ids
            // name a row to restore.
            u64::from_str_radix(id, 16)
                .ok()
                .and_then(|n| u32::try_from(n).ok())
        })
        .collect();
    restore_queue_rows(db, shape, min_age_minutes, &claimed_ns).await?;
    Ok(claimed_ns)
}

/// Feed state the drives may have moved since seeding — the bounded
/// live-window reset only: the growing 2018 history and the staging
/// hour's current-generation bulk are fixture truth that must persist
/// between probes; only the obsolete tail (strict `generation < 9`,
/// matching the seeded generations 7/9 — never an open `<> 9` walk
/// over the live prefix) and the staged counters a cleanup drive
/// could have disturbed are restored here (stow#523).
async fn rearm_feed_window(db: &DurableDb, shape: FixtureShape) -> Result<(), QueueError> {
    db.query(
        "DELETE FROM demand_feed_pages \
         WHERE hour = '2022-01-01T00' AND generation < 9",
    )
    .execute()
    .await
    .map_err(|error| QueueError::Sql(format!("reset staging obsolete tail: {error}")))?;
    db.query(include_str!("feed_obsolete_reseed.sql"))
        .bind(i64::from(feed_staged_pages(shape)))
        .bind(i64::from(feed_staged_pages(shape)))
        .bind(i64::from(feed_staged_pages(shape)))
        .execute()
        .await
        .map_err(|error| QueueError::Sql(format!("reseed staging obsolete tail: {error}")))?;
    db.query(
        "UPDATE demand_feed_hours SET staged_pages = ?, staged_entries = ? \
         WHERE hour = '2022-01-01T00'",
    )
    .bind(i64::from(feed_staged_pages(shape)))
    .bind(i64::from(feed_staged_pages(shape)) * 4)
    .execute()
    .await
    .map_err(|error| QueueError::Sql(format!("reset staging feed counters: {error}")))?;
    Ok(())
}

/// Restores the seeded queue the drives are calibrated on — outside
/// the measured window, the same precedent as the installation-token
/// seed. The contract is the seeded state, not just its shape: every
/// row and membership a probe moved must read exactly as the seed
/// wrote it, or the next `POST /budget` on this persisted fixture
/// measures a queue the drives were not calibrated for — a retry
/// drive whose two `failed` rows the last probe already re-entered
/// finds nothing to mutate.
///
/// - Inserted artifacts: every task the lanes and the probe itself
///   insert carries a content-derived `task_id`
///   (`crate-version-hash-target-rustc`), while seeded rows are
///   `printf('%064x', n)`, so `task_id LIKE '%-%'` isolates exactly the
///   rows a run added. The request drives' records die with them; the
///   two fixture records survive — `GET /requests/{id}` reads the
///   `enqueued` one.
/// - Mutated seeded rows: retry's failed pair, cancel's pair,
///   promote's miss-lane row, purge's deleted pair, the resync's row
///   101 and the complete-run target are re-written through the seed's
///   own column formulas ([`restore_queue_rows`]) — a row a probe moved
///   or deleted returns to seeded truth.
/// - Claimed rows: the pass records the ids its own claim moved out
///   of `pending` into probe control state
///   ([`record_probe_claimed`]); the re-arm restores exactly those
///   through the same seed upsert. A status- or band-scoped restore
///   could resurrect a row a load lane legitimately moved, so the set
///   is the recorded claim outcome, never a predicate over row
///   state. A claimed row a drive inserted dies in the `%-%` cleanup
///   — only seeded (hex) ids reach the upsert.
/// - Execution identities: restored rows receive fresh generations, so
///   failure evidence never collides across passes. The running target's
///   attempt advances, while the failure target resets to attempt 1 to
///   keep measuring the retry arm below the four-attempt cap.
/// - Row 101's edges: the resync's delta edge sync deleted the seeded
///   edge set and wrote its own; both edge phases re-seed the owner's
///   range after a delete (each `INSERT OR IGNORE` is idempotent).
/// - Slice membership: the delta report retires 30 of the
///   `(target[0], 1.85.0)` slice's rows and adds its own; the full
///   report publishes a dedicated `(target[8], 9.9.9)` slice. Only the
///   probe's rows move — `stow-gate-*` is a crate prefix no fixture or
///   load row carries — plus the delta's `applied_generation` bump and
///   the full report's marker, then the retire band re-seeds (`OR
///   IGNORE` rewrites only the missing rows; the loaded bulk's
///   publication is untouched).
/// - Persisted gate flags: dependents of every touched dep and the
///   restored pending rows recompute `deps_met`/`blocked` through the
///   production expressions — the pass's own refreshes answered for
///   the post-probe truth, and restored dep statuses must not leave
///   them stale.
pub async fn rearm(
    db: &DurableDb,
    shape: FixtureShape,
    min_age_minutes: u32,
) -> Result<(), QueueError> {
    for statement in [
        "DELETE FROM demand_batches",
        "DELETE FROM demand_contributions",
        // The hourly feed's staging/delivery state is fixture state
        // too — but only the live window: the 2018 bulk
        // [`seed_feed_bulk`] plants is the retained depth the feed
        // drives must measure against, while every probe-staged hour
        // lands at 2020+. The re-arm clears the live window and the
        // watermark the delivery drive advanced, then re-seeds the
        // bulk below (stow#523).
        "DELETE FROM demand_feed_pages WHERE hour >= '2019' AND hour < '2022'",
        "DELETE FROM demand_feed_hours WHERE hour >= '2019' AND hour < '2022'",
        "DELETE FROM settings WHERE key = 'demand_feed_watermark'",
        "DELETE FROM queue_dependencies WHERE task_id LIKE '%-%'",
        "DELETE FROM queue WHERE task_id LIKE '%-%'",
        "DELETE FROM requests WHERE request_id NOT IN \
         ('req-fixture-enqueued', 'req-fixture-failed')",
        // Each fixture phase starts with its intended cost state:
        // medians learned by an earlier phase must not leak into the
        // next one's rank.
        "DELETE FROM crate_build_samples",
        "DELETE FROM crate_build_stats",
    ] {
        db.query(statement)
            .execute()
            .await
            .map_err(|error| QueueError::Sql(format!("re-arm inserted rows: {error}")))?;
    }
    // The mutation drives' exact targets. `pending_row`/`failed_row`
    // and friends are the same positional helpers the drives select
    // with, so the restore cannot drift from the selectors.
    let restored = [
        101, // the resync's fixture identity (its edge set re-seeded below)
        FixtureShape::pending_row(701),
        FixtureShape::pending_row(702),
        FixtureShape::pending_row(4703),
        shape.failed_row(0),
        shape.failed_row(1),
        shape.completed_row(0),
        shape.completed_row(1),
        shape.running_row(),
        shape.dispatched_row(0),
    ];
    // The attempt the running target is at *before* the upsert rewrites
    // it to the seeded 1 — read first so the restore below can step the
    // epoch forward instead of letting the next pass reuse it.
    let running_attempt = db
        .query("SELECT attempt FROM queue WHERE task_id = printf('%064x', ?)")
        .bind(i64::from(shape.running_row()))
        .fetch_scalar_optional::<i64>()
        .await
        .map_err(|error| QueueError::Sql(format!("read running attempt: {error}")))?;
    restore_queue_rows(db, shape, min_age_minutes, &restored).await?;
    if let Some(attempt) = running_attempt {
        db.query("UPDATE queue SET attempt = ? WHERE task_id = printf('%064x', ?)")
            .bind(attempt + 1)
            .bind(i64::from(shape.running_row()))
            .execute()
            .await
            .map_err(|error| QueueError::Sql(format!("re-arm running attempt: {error}")))?;
    }
    // Whatever the last pass claimed — its own recorded outcome, kept
    // in `settings` under [`PROBE_CLAIMED_KEY`] so the set survives
    // between `POST /budget` calls.
    let claimed_ns = restore_claimed_rows(db, shape, min_age_minutes).await?;
    rearm_feed_window(db, shape).await?;
    // Row 101's seeded edge set: the resync's delta sync rewrote it.
    db.query("DELETE FROM queue_dependencies WHERE task_id = printf('%064x', ?)")
        .bind(101_i64)
        .execute()
        .await
        .map_err(|error| QueueError::Sql(format!("re-arm resync edges: {error}")))?;
    seed_edges_chunk(db, shape, SeedPhase::EdgesEvery, 100, 101).await?;
    seed_edges_chunk(db, shape, SeedPhase::EdgesThirds, 100, 101).await?;
    // The probe's publication — the full report's dedicated slice plus
    // the delta's added rows, then the delta's marker bump.
    for (statement, binds) in [
        (
            "DELETE FROM published_slice_rows WHERE crate_name LIKE 'stow-gate-%'",
            Vec::new(),
        ),
        (
            "DELETE FROM published_slices WHERE target = ? AND rustc_version = '9.9.9'",
            vec![CI_TARGET_TRIPLES[8].to_owned()],
        ),
        (
            "UPDATE published_slices SET generation = 1, applied_generation = 0 \
             WHERE target = ? AND rustc_version = '1.85.0'",
            vec![CI_TARGET_TRIPLES[0].to_owned()],
        ),
    ] {
        let mut query = db.query(statement);
        for bind in binds {
            query = query.bind(bind);
        }
        query
            .execute()
            .await
            .map_err(|error| QueueError::Sql(format!("re-arm slice tables: {error}")))?;
    }
    // The retire band the delta report clears — `slice_first_row` +
    // `slice_live_rows` produce the same member list the report walks.
    // `OR IGNORE` makes the chunk write only the rows the retire
    // actually removed.
    let live = shape.slice_live_rows(0);
    let first = shape.slice_first_row(0);
    let retire_lo = first + (live - super::drives::DELTA_ROWS) * 9 - 1;
    let retire_hi = first + (live - 1) * 9;
    seed_slice_chunk(db, retire_lo, retire_hi).await?;
    // Persisted gate flags on the restored pending rows and on the
    // dependents of every dep a drive touched — recomputed through the
    // same expressions the production transitions use, over a set
    // bounded by the touched ids, not by the queue.
    let mut touched: Vec<u32> = restored.to_vec();
    touched.extend_from_slice(&claimed_ns);
    for i in 0..super::drives::DELTA_ROWS {
        touched.push(first + (live - 1 - i) * 9);
    }
    refresh_rearm_gate_state(db, &touched).await?;
    Ok(())
}

/// The `requests` fixture the `/requests` drives read (stow#428): one
/// `enqueued` record whose stored roots name real queue rows — a pending
/// human row (the status read's `human_lane_position` probe), a
/// completed row (`cached` arm) and a no-library root — and one `failed`
/// record, the backstop's terminal state. Inserted when the `Queue`
/// phase finishes so the ids it names exist.
pub async fn seed_requests(db: &DurableDb, shape: FixtureShape) -> Result<(), QueueError> {
    let pending_root =
        stow_types::fixture::task_hex_id(u64::from(FixtureShape::HUMAN_LANE_ROWS - 5));
    // Row 5 stays clear of the purge drive's row-0/1 deletes, which run
    // before `GET /requests/{id}` re-probes this root.
    let completed_root = stow_types::fixture::task_hex_id(u64::from(shape.completed_row(5)));
    let outcome = serde_json::json!([
        {
            "target": CI_TARGET_TRIPLES[0],
            "task_id": pending_root,
            "cached": false,
            "was_queued": false,
        },
        {
            "target": CI_TARGET_TRIPLES[1],
            "task_id": completed_root,
            "cached": false,
            "was_queued": true,
        },
        {
            "target": CI_TARGET_TRIPLES[2],
            "task_id": null,
            "cached": false,
            "was_queued": false,
        },
    ])
    .to_string();
    db.query(
        "INSERT OR IGNORE INTO requests (request_id, attempt, crate_name, version, features_json, \
         rustc_version, state, dispatched_at, github_run_id, github_run_url, \
         outcome_json, error) \
         VALUES (?, 1, 'serde', '1.0.0', '[]', '1.86.0', 'enqueued', 0, \
                 '42', 'https://github.com/water-rs/stow/actions/runs/42', ?, NULL), \
                (?, 2, 'clap', '1.0.0', '[]', '1.86.0', 'failed', 0, \
                 '43', 'https://github.com/water-rs/stow/actions/runs/43', NULL, ?)",
    )
    .bind(REQUEST_FIXTURE_ENQUEUED)
    .bind(outcome)
    .bind(REQUEST_FIXTURE_FAILED)
    .bind("resolve run concluded 'failure' (https://github.com/water-rs/stow/actions/runs/43)")
    .execute()
    .await
    .map_err(|error| format!("seed request rows: {error}"))?;
    Ok(())
}

/// The counted table a phase's chunk writes — the counter the cursor
/// advances for it. `DepsMet` only updates, so it reports no table.
pub const fn counted_table(phase: SeedPhase) -> Option<CountedTable> {
    match phase {
        SeedPhase::Queue => Some(CountedTable::Queue),
        SeedPhase::EdgesEvery | SeedPhase::EdgesThirds => Some(CountedTable::Dependencies),
        SeedPhase::Slices => Some(CountedTable::Slices),
        // The feed phases write internal bulk the seed report does
        // not count — the three-counter codec stays untouched.
        SeedPhase::Nodes
        | SeedPhase::DepsMet
        | SeedPhase::FeedHeaders
        | SeedPhase::FeedPages
        | SeedPhase::FeedStaged => None,
    }
}

/// What one [`seed_batch`] chunk call did.
#[derive(Debug, Clone, Copy)]
pub struct SeedStep {
    /// The phase the cursor resumes from (the next phase once this one
    /// finished).
    pub phase: SeedPhase,
    /// The `n` the cursor resumes at.
    pub n: u32,
    /// The seed is finished.
    pub done: bool,
    /// The chunk wrote or updated fixture state (its range was
    /// non-empty at this `n`).
    pub wrote: bool,
    /// Edge records the chunk actually inserted — measured by
    /// `SELECT changes()`, the only counter a position cannot derive,
    /// since `OR IGNORE` skips deps an earlier owner already wrote.
    /// Zero outside the edge phases.
    pub edges_written: u64,
}

/// Seed one `(n, n + batch]` chunk of `phase` and return where the seed
/// resumes — the next phase (or `None` once `DepsMet` finishes).
pub async fn seed_batch(
    db: &DurableDb,
    shape: FixtureShape,
    phase: SeedPhase,
    n: u32,
    batch: u32,
    min_age_minutes: u32,
) -> Result<SeedStep, QueueError> {
    let hi = (n + batch).min(phase.range_end(shape));
    let mut edges_written = 0u64;
    let wrote = hi > n;
    if wrote {
        match phase {
            SeedPhase::Queue => {
                seed_queue_chunk(db, shape, n, hi, min_age_minutes).await?;
                if hi >= phase.range_end(shape) {
                    seed_requests(db, shape).await?;
                }
            }
            SeedPhase::EdgesEvery | SeedPhase::EdgesThirds => {
                edges_written = seed_edges_chunk(db, shape, phase, n, hi).await?;
            }
            SeedPhase::Slices => {
                seed_slice_chunk(db, n.max(phase.range_start(shape)), hi).await?;
                if hi >= phase.range_end(shape) {
                    seed_slice_headers(db).await?;
                }
            }
            SeedPhase::Nodes => seed_nodes_chunk(db, n, hi).await?,
            SeedPhase::DepsMet => seed_deps_met_chunk(db, n, hi).await?,
            SeedPhase::FeedHeaders => seed_feed_headers_chunk(db, n, hi).await?,
            SeedPhase::FeedPages => {
                seed_feed_pages_chunk(db, feed_hist_hours(shape), n, hi).await?;
            }
            SeedPhase::FeedStaged => {
                if n == 0 {
                    seed_feed_staging_header(db, shape).await?;
                }
                seed_feed_staged_chunk(db, feed_staged_pages(shape), n, hi).await?;
                if hi >= phase.range_end(shape) {
                    fix_feed_staging_counters(db, shape).await?;
                }
            }
        }
    }
    let (next_phase, next_n, done) = if hi >= phase.range_end(shape) {
        phase.next().map_or((phase, hi, true), |next| {
            (next, next.range_start(shape), false)
        })
    } else {
        (phase, hi, false)
    };
    Ok(SeedStep {
        phase: next_phase,
        n: next_n,
        done,
        wrote,
        edges_written,
    })
}

/// The obsolete-generation tail the staging bulk hour always
/// carries — the bounded retire target the begin/cleanup drives
/// measure against.
const FEED_OBSOLETE_TAIL: u32 = 256;

/// `queue_rows/512` delivered headers (clamped `8–4_000`) — the
/// retained feed history the index probes must skip, not scan.
pub fn feed_hist_hours(shape: FixtureShape) -> u32 {
    (shape.queue_rows / 512).clamp(8, 4_000)
}

/// `queue_rows/8` retained delivered pages (clamped `64–160_000`).
fn feed_hist_pages(shape: FixtureShape) -> u32 {
    (shape.queue_rows / 8).clamp(64, 160_000)
}

/// `queue_rows/16` current-generation pages on the staging hour
/// (clamped `32–64_000`) — the live bulk the none-obsolete cleanup
/// drive's predicate must walk past without matching.
pub fn feed_staged_pages(shape: FixtureShape) -> u32 {
    (shape.queue_rows / 16).clamp(32, 64_000)
}

/// One bounded `FeedHeaders` chunk: historical delivered headers
/// rolling from 2018-01-01, `INSERT OR IGNORE` so a replayed cursor
/// dedupes instead of rewriting.
async fn seed_feed_headers_chunk(db: &DurableDb, n: u32, hi: u32) -> Result<(), QueueError> {
    if hi <= n {
        return Ok(());
    }
    db.query(include_str!("feed_bulk_headers.sql"))
        .bind(i64::from(n) + 1)
        .bind(i64::from(hi))
        .execute()
        .await
        .map_err(|error| QueueError::Sql(format!("seed feed headers: {error}")))?;
    Ok(())
}

/// One bounded `FeedPages` chunk: retained applied pages spread over
/// `hist_hours` delivered headers.
async fn seed_feed_pages_chunk(
    db: &DurableDb,
    hist_hours: u32,
    n: u32,
    hi: u32,
) -> Result<(), QueueError> {
    if hi <= n {
        return Ok(());
    }
    db.query(include_str!("feed_bulk_pages.sql"))
        .bind(i64::from(n) + 1)
        .bind(i64::from(hi))
        .bind(i64::from(hist_hours))
        .bind(i64::from(hist_hours))
        .bind(i64::from(hist_hours))
        .execute()
        .await
        .map_err(|error| QueueError::Sql(format!("seed retained feed pages: {error}")))?;
    Ok(())
}

/// One bounded `FeedStaged` chunk: current-generation (9) rows up to
/// `staged_pages`, then the 256-row obsolete (7) tail — the staging
/// bulk hour '2022-01-01T00' sits above every hour a drive can
/// deliver, since an unfinished hour below the delivered one blocks
/// the contiguous-watermark transition.
async fn seed_feed_staged_chunk(
    db: &DurableDb,
    staged_pages: u32,
    n: u32,
    hi: u32,
) -> Result<(), QueueError> {
    if hi <= n {
        return Ok(());
    }
    db.query(include_str!("feed_bulk_staged.sql"))
        .bind(i64::from(n) + 1)
        .bind(i64::from(hi))
        .bind(i64::from(staged_pages))
        .execute()
        .await
        .map_err(|error| QueueError::Sql(format!("seed staging feed pages: {error}")))?;
    Ok(())
}

/// The staging bulk header — written on the `FeedStaged` cursor's
/// first chunk so the page rows' hour foreign key resolves.
async fn seed_feed_staging_header(db: &DurableDb, shape: FixtureShape) -> Result<(), QueueError> {
    let staged = i64::from(feed_staged_pages(shape));
    db.query(
        "INSERT OR IGNORE INTO demand_feed_hours \
         (hour, generation, state, staged_pages, staged_entries) \
         VALUES ('2022-01-01T00', 9, 'staging', ?, ?)",
    )
    .bind(staged)
    .bind(staged * 4)
    .execute()
    .await
    .map_err(|error| QueueError::Sql(format!("seed staging feed header: {error}")))?;
    Ok(())
}

/// The staging header's exact staged counters once the `FeedStaged`
/// cursor finishes — the page-insert trigger counts the obsolete
/// tail too; the header's truth is the current generation alone.
async fn fix_feed_staging_counters(db: &DurableDb, shape: FixtureShape) -> Result<(), QueueError> {
    let staged = i64::from(feed_staged_pages(shape));
    db.query(
        "UPDATE demand_feed_hours SET staged_pages = ?, staged_entries = ? \
         WHERE hour = '2022-01-01T00'",
    )
    .bind(staged)
    .bind(staged * 4)
    .execute()
    .await
    .map_err(|error| QueueError::Sql(format!("fix staging feed counters: {error}")))?;
    Ok(())
}

/// Seed the whole fixture on the host path — the same chunks the/// Seed the whole fixture on the host path — the same chunks the
/// workerd probe writes, looped until the seed reports done.
///
/// # Errors
/// Returns `QueueError::Sql` if any seed statement fails.
#[cfg(test)]
pub async fn seed_production_shape(
    db: &DurableDb,
    shape: &FixtureShape,
    min_age_minutes: u32,
) -> Result<(), QueueError> {
    let mut phase = SeedPhase::Queue;
    let mut n = phase.range_start(*shape);
    loop {
        let step = seed_batch(db, *shape, phase, n, SEED_BATCH_ROWS, min_age_minutes).await?;
        if step.done {
            return Ok(());
        }
        phase = step.phase;
        n = step.n;
    }
}

/// The `settings` row carrying the seed cursor —
/// `"<tag>:<n>:<queue_rows>:<queue>,<deps>,<slices>"` with tag `reset`
/// (n = rows wiped so far — monotonic per working call), `queue`,
/// `edges_every`, `edges_thirds`, `slices`, `deps` or `done` (n = 0)
/// and the trailing field the counted fixture
/// tables' row totals ([`SeedCounts`]). Each call advances it
/// by at most one [`SEED_BATCH_ROWS`] chunk, so a seed
/// survives the per-request work ceiling a whole 100k-row fixture
/// would hit; the counters ride in the same statement the cursor's
/// position commits with, so a reply lost between them cannot split
/// the progress record. The stored shape gates reuse: a cursor for a
/// different `queue_rows` restarts the seed rather than resuming into
/// a fixture whose rows describe another shape.
const SEED_CURSOR_KEY: &str = "budget_seed";

/// Tables `reset` clears, in child-before-parent order.
const SEED_TABLES: &[&str] = &[
    "queue_dependencies",
    "published_slice_rows",
    "published_slices",
    "requests",
    "queue",
];

/// `POST /budget/seed` — load the fixture through the operator path,
/// one cursor step per call. The schema is the operator migrate
/// route's product — the harness runs it before seeding, and request
/// code neither issues DDL nor re-checks the migration's queue-wide
/// passes (a `queue::migrate` inside every chunk call walked the
/// growing queue for a no-op `!=` guard — the linear request cost that
/// outlived the dev proxy's reply window at 1M rows). `reset` restarts
/// the cursor and clears the fixture's tables chunk by chunk. Callers
/// loop until `done`; a finished (or hand-populated) queue reports
/// `done = true, seeded = false` unless `reset` is passed.
pub async fn seed(
    db: &DurableDb,
    request: &SchedulerSeedRequest,
    settings: &crate::scheduler::queue::SchedulerSettings,
) -> Result<SchedulerSeedReport, QueueError> {
    let shape = FixtureShape {
        queue_rows: request
            .queue_rows
            .unwrap_or(FixtureShape::PRODUCTION.queue_rows),
    };
    let batch = request
        .batch
        .unwrap_or(SEED_BATCH_ROWS)
        .clamp(1, SEED_BATCH_ROWS * 4);
    // The counters name what the counted tables hold. They are
    // measured once per cursor birth — a reset's starting sizes, a
    // fresh seed's empties, a populated queue's report — and never
    // again: the step's own write deltas carry them forward, which is
    // what the per-call `COUNT(*)` re-scans used to do at the cost of
    // a full-table walk per request.
    let (cursor, counts) = match (request.reset.unwrap_or(false), read_seed_cursor(db).await?) {
        (false, Some(cursor)) if seed_cursor_shape(&cursor)? == shape.queue_rows => {
            // The counters resume from the cursor row itself — it is
            // internal operator state, so a malformed value is an
            // error, not a case to recover.
            let counts = seed_cursor_counts(&cursor)?;
            (cursor, counts)
        }
        (true, _) | (false, Some(_)) => {
            // `reset` restarts the wipe; a cursor written for a
            // different `queue_rows` does the same — its chunks
            // describe another shape.
            let counts = measure_seed_counts(db).await?;
            (
                format!("reset:0:{}:{}", shape.queue_rows, counts.encode()),
                counts,
            )
        }
        (false, None) => {
            // No cursor: a populated queue is a fixture seeded before
            // cursors existed (or by hand) — report done rather than
            // double-seed; an empty one starts at the queue phase.
            let counts = measure_seed_counts(db).await?;
            let tag = if counts.queue == 0 { "queue" } else { "done" };
            (
                format!("{tag}:0:{}:{}", shape.queue_rows, counts.encode()),
                counts,
            )
        }
    };
    let (next, seeded, counts) = run_seed_step(
        db,
        shape,
        &cursor,
        batch,
        settings.dispatch_min_age_minutes,
        counts,
    )
    .await?;
    if next != cursor {
        set_seed_cursor(db, &next).await?;
    }
    // The cursor's `tag:n:shape:counts` head is the caller's progress
    // witness — our own format, so the split cannot fail.
    let mut head = next.split(':');
    let phase = head.next().expect("cursor tag").to_owned();
    let n = head
        .next()
        .and_then(|position| position.parse::<u64>().ok())
        .expect("cursor position");
    Ok(SchedulerSeedReport {
        queue_rows: counts.queue,
        dependency_rows: counts.dependencies,
        slice_rows: counts.slices,
        seeded,
        done: next.starts_with("done:"),
        phase,
        n,
    })
}

/// One cursor step: clear one `reset` table chunk, or write one fixture
/// chunk and return the cursor it resumes from, counters updated by the
/// step's position and measured write deltas. `seeded` reports whether
/// the step advanced fixture readiness (a wipe or finished seed does
/// not).
async fn run_seed_step(
    db: &DurableDb,
    shape: FixtureShape,
    cursor: &str,
    batch: u32,
    min_age_minutes: u32,
    mut counts: SeedCounts,
) -> Result<(String, bool, SeedCounts), QueueError> {
    let (tag, n, _, _) = parse_seed_cursor(cursor)?;
    if tag == "done" {
        return Ok((cursor.to_owned(), false, counts));
    }
    if tag == "reset" {
        // The reset position counts rows wiped so far — every call that
        // deletes advances `n`, so a caller bounding itself on progress
        // sees movement on each working call. The table under the wipe
        // is re-resolved per call: the first fixture table still holding
        // rows. A counted table's emptiness reads straight off its
        // counter (the wipe's own DELETEs keep it exact); an uncounted
        // table asks a one-row probe — `COUNT(*)` per chunk re-read the
        // whole table being cleared.
        let mut table = None;
        for candidate in SEED_TABLES {
            let has_rows = match CountedTable::for_table(candidate) {
                Some(counted) => counts.get(counted) > 0,
                None => db
                    .query(&format!("SELECT 1 FROM {candidate} LIMIT 1"))
                    .fetch_scalar_optional::<i64>()
                    .await
                    .map_err(|error| QueueError::Sql(format!("probe {candidate} empty: {error}")))?
                    .is_some(),
            };
            if has_rows {
                table = Some(candidate);
                break;
            }
        }
        let Some(table) = table else {
            // Every fixture table is clear — the wipe hands off to the
            // queue phase. `seeded` reports fixture readiness progress:
            // a wipe writes none, so it stays false until a seed chunk
            // runs.
            return Ok((
                format!("queue:0:{}:{}", shape.queue_rows, counts.encode()),
                false,
                counts,
            ));
        };
        // `IN (SELECT rowid … LIMIT)` rather than `DELETE … LIMIT` — the
        // latter needs a compile-time extension workerd does not ship.
        db.query(&format!(
            "DELETE FROM {table} WHERE rowid IN \
             (SELECT rowid FROM {table} LIMIT {batch})"
        ))
        .execute()
        .await
        .map_err(|error| QueueError::Sql(format!("reset {table}: {error}")))?;
        let wiped = crate::scheduler::queue::changes(db).await?;
        if let Some(counted) = CountedTable::for_table(table) {
            counts.subtract(counted, wiped)?;
        }
        return Ok((
            format!(
                "reset:{}:{}:{}",
                u64::from(n) + wiped,
                shape.queue_rows,
                counts.encode()
            ),
            false,
            counts,
        ));
    }
    let phase = parse_seed_phase(tag)
        .ok_or_else(|| QueueError::Sql(format!("bad seed cursor {cursor}")))?;
    let step = seed_batch(db, shape, phase, n, batch, min_age_minutes).await?;
    // The position this phase reached: `step.n` is the NEXT phase's
    // start on a boundary, so an ended phase takes its own range end.
    let phase_n = if step.phase == phase && !step.done {
        step.n
    } else {
        phase.range_end(shape)
    };
    match counted_table(phase) {
        // Position-derived: the table was empty when the phase began and
        // each chunk inserts its whole range atomically (`OR IGNORE`
        // only skips replayed rows), so the position IS the row count —
        // no arithmetic to drift.
        Some(CountedTable::Queue) => {
            counts.set(CountedTable::Queue, u64::from(phase_n));
        }
        // Two stored rows per completed node — the `required_unit_shapes`
        // pair the slice seed publishes.
        Some(CountedTable::Slices) => counts.set(
            CountedTable::Slices,
            u64::from(phase_n - shape.pending_end()) * 2,
        ),
        // `changes()`-tracked: `OR IGNORE` skips deps another owner
        // already wrote, so inserts are a measured delta, not a range.
        Some(CountedTable::Dependencies) => {
            counts.add(CountedTable::Dependencies, step.edges_written)?;
        }
        None => {}
    }
    let next_tag = if step.done {
        "done"
    } else {
        seed_phase_tag(step.phase)
    };
    Ok((
        format!(
            "{next_tag}:{}:{}:{}",
            step.n,
            shape.queue_rows,
            counts.encode()
        ),
        step.wrote,
        counts,
    ))
}

/// The phase tag of a seed cursor value.
const fn seed_phase_tag(phase: SeedPhase) -> &'static str {
    match phase {
        SeedPhase::Queue => "queue",
        SeedPhase::EdgesEvery => "edges_every",
        SeedPhase::EdgesThirds => "edges_thirds",
        SeedPhase::Nodes => "nodes",
        SeedPhase::Slices => "slices",
        SeedPhase::DepsMet => "deps",
        SeedPhase::FeedHeaders => "feed_headers",
        SeedPhase::FeedPages => "feed_pages",
        SeedPhase::FeedStaged => "feed_staged",
    }
}

/// The inverse of [`seed_phase_tag`].
fn parse_seed_phase(tag: &str) -> Option<SeedPhase> {
    match tag {
        "queue" => Some(SeedPhase::Queue),
        "edges_every" => Some(SeedPhase::EdgesEvery),
        "edges_thirds" => Some(SeedPhase::EdgesThirds),
        "nodes" => Some(SeedPhase::Nodes),
        "slices" => Some(SeedPhase::Slices),
        "deps" => Some(SeedPhase::DepsMet),
        "feed_headers" => Some(SeedPhase::FeedHeaders),
        "feed_pages" => Some(SeedPhase::FeedPages),
        "feed_staged" => Some(SeedPhase::FeedStaged),
        _ => None,
    }
}

/// `"<tag>:<n>:<queue_rows>:<queue>,<deps>,<slices>"` → its parts;
/// every cursor variant carries the shape it was seeded with and the
/// counted tables' totals, so a resume never re-scans for them. The
/// cursor is internal operator state — anything not in this shape is
/// corruption the call fails on, not a legacy form to translate.
fn parse_seed_cursor(cursor: &str) -> Result<(&str, u32, u32, SeedCounts), QueueError> {
    let bad = || QueueError::Sql(format!("bad seed cursor {cursor}"));
    let mut parts = cursor.split(':');
    let (tag, n, rows, counts_field) = (
        parts.next().ok_or_else(bad)?,
        parts.next().ok_or_else(bad)?,
        parts.next().ok_or_else(bad)?,
        parts.next().ok_or_else(bad)?,
    );
    if parts.next().is_some() {
        return Err(bad());
    }
    Ok((
        tag,
        n.parse().map_err(|_| bad())?,
        rows.parse().map_err(|_| bad())?,
        SeedCounts::decode(counts_field)?,
    ))
}

/// The cursor's counted-table totals.
fn seed_cursor_counts(cursor: &str) -> Result<SeedCounts, QueueError> {
    parse_seed_cursor(cursor).map(|(_, _, _, counts)| counts)
}

/// The counted tables' live sizes — the one `COUNT(*)` each table pays
/// per seed, run at cursor birth or when resuming a pre-counter cursor.
async fn measure_seed_counts(db: &DurableDb) -> Result<SeedCounts, QueueError> {
    Ok(SeedCounts {
        queue: count_rows(db, "queue").await?,
        dependencies: count_rows(db, "queue_dependencies").await?,
        slices: count_rows(db, "published_slice_rows").await?,
    })
}

/// The `queue_rows` a cursor was written for, if it parses.
pub fn seed_cursor_shape(cursor: &str) -> Result<u32, QueueError> {
    parse_seed_cursor(cursor).map(|(_, _, rows, _)| rows)
}

pub async fn read_seed_cursor(db: &DurableDb) -> Result<Option<String>, QueueError> {
    db.query(&format!(
        "SELECT value FROM settings WHERE key = '{SEED_CURSOR_KEY}'"
    ))
    .fetch_scalar_optional::<String>()
    .await
    .map_err(|error| QueueError::Sql(format!("read seed cursor: {error}")))
}

async fn set_seed_cursor(db: &DurableDb, cursor: &str) -> Result<(), QueueError> {
    db.query(&format!(
        "INSERT INTO settings (key, value) VALUES ('{SEED_CURSOR_KEY}', ?) \
         ON CONFLICT (key) DO UPDATE SET value = excluded.value"
    ))
    .bind(cursor.to_owned())
    .execute()
    .await
    .map_err(|error| QueueError::Sql(format!("write seed cursor: {error}")))?;
    Ok(())
}

pub async fn count_rows(db: &DurableDb, table: &str) -> Result<u64, QueueError> {
    db.query(&format!("SELECT COUNT(*) AS n FROM {table}"))
        .fetch_scalar::<i64>()
        .await
        .map(|n| n.max(0).cast_unsigned())
        .map_err(|error| QueueError::Sql(format!("count {table}: {error}")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scheduler::test_db::memory_db;

    /// The gate's own loop shape (admin/src/scheduler.rs): `seed`
    /// called until `done` with `reset` on the first call only, and a
    /// call that returns the same `(phase, n)` twice while `!done` is
    /// a stall. A seed at one size then a reset seed at another —
    /// small batch, so the wipe takes several calls per table — is
    /// the shape whose reset position must advance on every working
    /// call (it counts rows wiped, not the table under the wipe).
    #[tokio::test]
    async fn seed_then_reset_seed_advances_progress_every_call() {
        let db = crate::scheduler::test_db::memory_db()
            .await
            .expect("memory db");
        let settings = crate::scheduler::queue::SchedulerSettings::default();

        // The admin loop verbatim: `reset` rides the first call, the
        // loop ends on `done`, and an unchanged (phase, n) is the
        // stall that fails fast.
        let run = |reset, queue_rows| {
            let db = &db;
            let settings = &settings;
            async move {
                let mut first = true;
                let mut progress: Option<(String, u64)> = None;
                let mut reset_ns: Vec<u64> = Vec::new();
                loop {
                    let report = seed(
                        db,
                        &SchedulerSeedRequest {
                            queue_rows: Some(queue_rows),
                            reset: Some(reset && first),
                            batch: Some(50),
                        },
                        settings,
                    )
                    .await
                    .expect("seed call");
                    first = false;
                    if report.phase == "reset" {
                        reset_ns.push(report.n);
                    }
                    let position = (report.phase.clone(), report.n);
                    assert!(
                        report.done || progress.as_ref() != Some(&position),
                        "seed stalled: phase={} n={} unchanged across calls",
                        report.phase,
                        report.n
                    );
                    progress = Some(position);
                    if report.done {
                        return (report, reset_ns);
                    }
                }
            }
        };

        let (report, _) = run(false, 200).await;
        assert_eq!(report.queue_rows, 200, "first seed's row count");

        let (report, reset_ns) = run(true, 320).await;
        assert_eq!(report.queue_rows, 320, "reset seed's row count");
        assert!(
            reset_ns.len() > 5 && reset_ns.windows(2).all(|pair| pair[1] > pair[0]),
            "reset's n is rows wiped so far — strictly increasing across calls: {reset_ns:?}"
        );
    }

    /// The cursor's counts field round-trips and rejects anything that
    /// is not three `u64`s — it is internal operator state, so a
    /// malformed field is corruption, never a legacy shape.
    #[test]
    fn seed_counts_codec() {
        let counts = SeedCounts {
            queue: 1_000_000,
            dependencies: 799_994,
            slices: 350_000,
        };
        assert_eq!(
            SeedCounts::decode(&counts.encode()).expect("round-trip"),
            counts
        );
        for bad in ["", "1,2", "1,2,3,4", "a,2,3", "1,2,3x", "1,2,3 "] {
            assert!(SeedCounts::decode(bad).is_err(), "{bad:?} decoded");
        }
    }

    /// `SELECT changes()` names the records a statement actually wrote —
    /// the counter source the backend's billed `rows_written` cannot
    /// be, since workerd folds index writes into it. A replayed `OR
    /// IGNORE` chunk reports only the rows it inserted: the first run
    /// writes the whole range, a partial re-run only the unwritten
    /// tail, and a full replay nothing at all.
    #[tokio::test]
    async fn edge_chunk_counts_only_inserted_records() {
        let db = memory_db().await.expect("memory db");
        let shape = FixtureShape { queue_rows: 400 };
        let written = seed_edges_chunk(&db, shape, SeedPhase::EdgesEvery, 0, 200)
            .await
            .expect("edges");
        assert_eq!(written, 200, "a fresh chunk inserts its whole range");
        let resumed = seed_edges_chunk(&db, shape, SeedPhase::EdgesEvery, 100, 300)
            .await
            .expect("overlapping chunk");
        assert_eq!(
            resumed, 100,
            "an overlapping chunk counts only its unwritten tail"
        );
        let replay = seed_edges_chunk(&db, shape, SeedPhase::EdgesEvery, 0, 300)
            .await
            .expect("replay");
        assert_eq!(replay, 0, "a replay inserts nothing");
        let rows: i64 = db
            .query("SELECT count(*) FROM queue_dependencies")
            .fetch_scalar()
            .await
            .expect("count");
        assert_eq!(rows, 300, "the table holds exactly the written union");
    }

    /// Queue and slice chunks replay idempotently too — the derived
    /// position counters stay exact after a cursor-commit loss because
    /// the re-run completes the same range.
    #[tokio::test]
    async fn queue_and_slice_chunks_replay_idempotently() {
        let db = memory_db().await.expect("memory db");
        let shape = FixtureShape { queue_rows: 400 };
        seed_queue_chunk(&db, shape, 0, 100, 0)
            .await
            .expect("queue chunk");
        seed_queue_chunk(&db, shape, 0, 100, 0)
            .await
            .expect("queue replay");
        let rows: i64 = db
            .query("SELECT count(*) FROM queue")
            .fetch_scalar()
            .await
            .expect("count");
        assert_eq!(rows, 100, "a replayed queue chunk adds nothing");
        seed_slice_chunk(&db, 200, 300).await.expect("slice chunk");
        seed_slice_chunk(&db, 200, 300).await.expect("slice replay");
        let rows: i64 = db
            .query("SELECT count(*) FROM published_slice_rows")
            .fetch_scalar()
            .await
            .expect("count");
        // Two stored rows per node — the `required_unit_shapes` pair.
        assert_eq!(rows, 200, "a replayed slice chunk adds nothing");
    }

    /// One edge joined to its owner and dep queue rows — the stored
    /// requirement columns against the facts production computes them
    /// from.
    #[derive(Debug, skyzen::FromRow)]
    struct EdgeRequirement {
        owner_target: String,
        owner_side: i64,
        dep_target: String,
        dep_side: i64,
        stored_side: i64,
        invocations: i64,
        shapes: i64,
    }
    /// One stored slice row joined to its node's queue facts.
    #[derive(Debug, skyzen::FromRow)]
    struct SliceMembership {
        target: String,
        host_side: i64,
        unit_side: i64,
        unit_invocation: i64,
        unit_linked: i64,
    }

    /// A node's invocation spelling — `for_task` on its target against
    /// the family's host triple, the same input `required_unit_shapes`
    /// takes.
    fn node_invocation(target: &str) -> stow_types::public_cache::UnitInvocation {
        stow_types::api::runner_family(target).map_or(
            stow_types::public_cache::UnitInvocation::Native,
            |family| {
                stow_types::public_cache::UnitInvocation::for_task(target, family.host_triple())
            },
        )
    }

    /// The seeded fixture's three consistency sweeps — edge identity
    /// against the joined queue row, edge requirements against
    /// production's `dep_edge_requirements`, and slice membership
    /// against `required_unit_shapes` — run once per test phase so a
    /// chunk replay is checked against the same contract as the fresh
    /// seed.
    async fn assert_edge_fixture(db: &DurableDb, label: &str) {
        assert_edge_identity(db, label).await;
        assert_edge_requirements(db, label).await;
        assert_slice_membership(db, label).await;
    }

    /// Every stored dep column equals the row `depends_on_task_id`
    /// joins to — stored values compared, never the formula that
    /// generated them.
    async fn assert_edge_identity(db: &DurableDb, label: &str) {
        const MISMATCH: &str = "SELECT count(*) FROM queue_dependencies d \
            JOIN queue q ON q.task_id = d.depends_on_task_id WHERE ";
        // Identity: every stored dep column equals the row
        // `depends_on_task_id` joins to — stored values compared,
        // never the formula that generated them.
        for (column, pair) in [
            ("crate", "d.dep_crate_name != q.crate_name"),
            ("version", "d.dep_version != q.version"),
            ("features", "d.dep_features_json != q.features_json"),
            ("target", "d.dep_target != q.target"),
            ("rustc", "d.dep_rustc_version != q.rustc_version"),
            ("host_side", "d.dep_host_side != q.host_side"),
        ] {
            let mismatches: i64 = db
                .query(&format!("{MISMATCH} {pair}"))
                .fetch_scalar()
                .await
                .expect("join");
            assert_eq!(mismatches, 0, "{label} {column} mismatches");
        }
    }

    /// `dep_invocations`/`dep_shapes` equal production's
    /// `dep_edge_requirements` over the joined owner/dep facts —
    /// every edge class present: host and target deps, native and
    /// cross invocation families, both owner sides (no edge carries
    /// `(1, 1)`).
    async fn assert_edge_requirements(db: &DurableDb, label: &str) {
        let edges = db
            .query(
                "SELECT o.target AS owner_target, o.host_side AS owner_side, \
                        d.target AS dep_target, d.host_side AS dep_side, \
                        e.dep_host_side AS stored_side, \
                        e.dep_invocations AS invocations, e.dep_shapes AS shapes \
                 FROM queue_dependencies e \
                 JOIN queue o ON o.task_id = e.task_id \
                 JOIN queue d ON d.task_id = e.depends_on_task_id",
            )
            .fetch_all::<EdgeRequirement>()
            .await
            .expect("edge requirements");
        assert!(!edges.is_empty(), "{label}: no edges joined");
        for edge in &edges {
            assert_eq!(edge.stored_side, edge.dep_side, "{label}: stored side");
            assert_eq!(
                (edge.invocations, edge.shapes),
                crate::scheduler::queue::dep_edge_requirements(
                    &edge.owner_target,
                    edge.owner_side != 0,
                    &edge.dep_target,
                    edge.dep_side != 0,
                ),
                "{label}: requirements for {} dep {} (owner {})",
                edge.dep_side,
                edge.dep_target,
                edge.owner_target,
            );
        }
    }

    /// Every stored slice row is one of its node's
    /// `required_unit_shapes`, and every completed node carries its
    /// full pair — a node missing either shape is the probe, not the
    /// fixture's noise.
    async fn assert_slice_membership(db: &DurableDb, label: &str) {
        let membership = db
            .query(
                "SELECT s.target AS target, q.host_side AS host_side, \
                        s.unit_side AS unit_side, s.unit_invocation AS unit_invocation, \
                        s.unit_linked AS unit_linked \
                 FROM published_slice_rows s \
                 JOIN queue q ON q.crate_name = s.crate_name AND q.version = s.version \
                    AND q.features_json = s.features_json AND q.target = s.target \
                    AND q.rustc_version = s.rustc_version",
            )
            .fetch_all::<SliceMembership>()
            .await
            .expect("slice membership");
        assert!(!membership.is_empty(), "{label}: no slice rows joined");
        for row in &membership {
            let invocation = node_invocation(&row.target);
            let covered =
                stow_types::public_cache::required_unit_shapes(row.host_side != 0, invocation)
                    .iter()
                    .any(|shape| {
                        shape.side.to_int() == row.unit_side
                            && shape.invocation.to_int() == row.unit_invocation
                            && shape.kind.to_int() == row.unit_linked
                    });
            assert!(
                covered,
                "{label}: slice row ({},{},{}) of {} (host_side={}) is no required shape",
                row.unit_side, row.unit_invocation, row.unit_linked, row.target, row.host_side,
            );
        }
        let incomplete: i64 = db
            .query(
                "SELECT COUNT(*) FROM (\
                    SELECT q.task_id FROM queue q \
                    LEFT JOIN published_slice_rows s \
                      ON s.crate_name = q.crate_name AND s.version = q.version \
                     AND s.features_json = q.features_json AND s.target = q.target \
                     AND s.rustc_version = q.rustc_version \
                    WHERE q.status = 'completed' \
                    GROUP BY q.task_id HAVING COUNT(*) != 2)",
            )
            .fetch_scalar()
            .await
            .expect("slice completeness");
        assert_eq!(incomplete, 0, "{label}: completed nodes missing shapes");
    }

    /// The dep_* columns cache the dependency row's own identity — the
    /// values the `queue` seed wrote at the dep's `n`. Every seeded
    /// edge joins its `depends_on_task_id` to that row and must agree
    /// on every identity column; a mismatch means the edge formula
    /// stopped mirroring the row formula (an unparenthesized splice,
    /// a literal where the row varies). Covered for both edge phases
    /// and across a replay, which must add nothing and break nothing.
    #[tokio::test]
    async fn edge_dep_identity_matches_the_dependency_row() {
        let db = memory_db().await.expect("memory db");
        let shape = FixtureShape { queue_rows: 4_000 };
        seed_queue_chunk(&db, shape, 0, shape.queue_rows, 0)
            .await
            .expect("queue rows");
        seed_edges_chunk(&db, shape, SeedPhase::EdgesEvery, 0, shape.queue_rows)
            .await
            .expect("every edges");
        seed_edges_chunk(&db, shape, SeedPhase::EdgesThirds, 0, shape.queue_rows)
            .await
            .expect("thirds edges");
        seed_slice_chunk(&db, shape.pending_end(), shape.completed_end())
            .await
            .expect("slice rows");

        assert_edge_fixture(&db, "fresh every+thirds+slices").await;

        // Replay an overlapping chunk of each phase — OR IGNORE makes
        // the re-run a no-op, so the checks stay clean.
        seed_edges_chunk(&db, shape, SeedPhase::EdgesEvery, 1_000, 3_000)
            .await
            .expect("every replay");
        seed_edges_chunk(&db, shape, SeedPhase::EdgesThirds, 1_000, 3_000)
            .await
            .expect("thirds replay");
        seed_slice_chunk(&db, shape.pending_end() + 500, shape.completed_end() - 500)
            .await
            .expect("slice replay");
        assert_edge_fixture(&db, "replayed").await;
    }

    /// The `GET /tasks?crate=` drive's probe reads a name's pinned
    /// version set, not a slice of the table: `crate123` covers
    /// `n ∈ [6150, 6200)` — `CRATE_NAME_ROWS` rows — at every fixture
    /// size, and the lookup seeks the identity index rather than
    /// scanning.
    #[tokio::test]
    async fn crate_name_lookup_reads_a_pinned_version_set() {
        /// `EXPLAIN QUERY PLAN` detail rows — the plan text only.
        #[derive(Debug, skyzen::FromRow)]
        struct PlanRow {
            detail: String,
        }
        for queue_rows in [8_000u32, 15_000] {
            let db = memory_db().await.expect("memory db");
            let shape = FixtureShape { queue_rows };
            seed_queue_chunk(&db, shape, 0, queue_rows, 0)
                .await
                .expect("queue rows");
            let matches: i64 = db
                .query("SELECT count(*) FROM queue WHERE crate_name = 'crate123'")
                .fetch_scalar()
                .await
                .expect("count");
            assert_eq!(
                matches,
                i64::from(CRATE_NAME_ROWS),
                "crate123 cardinality at {queue_rows} rows"
            );
            let plan = db
                .query(
                    "EXPLAIN QUERY PLAN \
                     SELECT task_id FROM queue WHERE crate_name = 'crate123'",
                )
                .fetch_all::<PlanRow>()
                .await
                .expect("plan");
            assert!(
                plan.iter()
                    .any(|row| row.detail.starts_with("SEARCH queue")),
                "crate lookup does not seek at {queue_rows} rows: {plan:?}"
            );
            assert!(
                !plan.iter().any(|row| row.detail.starts_with("SCAN queue")),
                "crate lookup scans at {queue_rows} rows: {plan:?}"
            );
        }
    }
    /// The claimed set's node-store closure is pinned by the fixture
    /// (stow#588): every claimable row's edges point at the shared
    /// `completed_dep` leaf, so the walk's closure is `{claimed, leaf}`
    /// — depth 1 — and its node count is the claim count plus one, at
    /// every fixture size. The scale check's "alarm pass" rows read
    /// must move only with the claimed count, never with stored bulk;
    /// seed the gate's two fixture sizes and assert the closure is
    /// identical, node for node.
    #[tokio::test]
    async fn claimed_set_closure_is_size_invariant() {
        use crate::scheduler::queue::{CoverageOracle, SemanticTaskIdentity};
        struct NoCoverage;
        impl CoverageOracle for NoCoverage {
            fn covered(
                &self,
                _identities: &[SemanticTaskIdentity],
            ) -> impl std::future::Future<
                Output = Result<std::collections::BTreeSet<SemanticTaskIdentity>, QueueError>,
            > + Send {
                std::future::ready(Ok(std::collections::BTreeSet::new()))
            }
        }
        #[derive(Debug, skyzen::FromRow)]
        struct NodeRow {
            task_id: String,
            children_json: String,
        }
        // The pinned leaf each claimable row's edges point at —
        // `completed_dep` in `seed_edges_chunk`, `pending_end + 1`,
        // spelled with the fixture's `printf('%064x', n)` task id.
        let leaf_of = |shape: &FixtureShape| {
            stow_types::fixture::task_hex_id(u64::from(shape.pending_end()) + 1)
        };
        let mut measured: Vec<(usize, usize, usize)> = Vec::new();
        for queue_rows in [100_000u32, 1_000_000] {
            let db = memory_db().await.expect("memory db");
            let shape = FixtureShape { queue_rows };
            seed_production_shape(&db, &shape, 0).await.expect("seed");
            let settings = crate::scheduler::queue::SchedulerSettings {
                dispatch_min_age_minutes: 0,
                ..Default::default()
            };
            let claimed =
                crate::scheduler::queue::claim_dispatchable_tasks(&db, &settings, &NoCoverage)
                    .await
                    .expect("claim");
            assert!(!claimed.is_empty(), "{queue_rows} rows claimed nothing");
            // The real walk's BFS: union the claimed ids' `children_json`
            // level by level until the frontier empties.
            let mut union: std::collections::HashSet<String> =
                claimed.iter().map(|task| task.task_id.clone()).collect();
            let mut frontier = union.iter().cloned().collect::<Vec<_>>();
            let mut depth = 0usize;
            while !frontier.is_empty() {
                let json = serde_json::to_string(&frontier).expect("ids json");
                let rows = db
                    .query(
                        "SELECT task_id, children_json FROM task_nodes                          WHERE task_id IN (SELECT value FROM json_each(?))",
                    )
                    .bind(json)
                    .fetch_all::<NodeRow>()
                    .await
                    .expect("nodes");
                let mut next = Vec::new();
                for row in rows {
                    let children: Vec<String> =
                        serde_json::from_str(&row.children_json).expect("children");
                    next.extend(children.into_iter().filter(|id| union.insert(id.clone())));
                }
                depth += 1;
                frontier = next;
                assert!(depth < 64, "walk outran the cycle bound");
            }
            // Every claimable row's children are the shared leaf, so
            // the union is exactly `{claimed, leaf}`: claim count plus
            // one node, two fetch levels — identical shape at every
            // fixture size. Only the claim count itself moves (it is
            // bounded by open slots and the page budget, not by stored
            // bulk), so assert the closure's depth and per-claim size,
            // which is what the scale check's rows-read bound prices.
            let leaf = leaf_of(&shape);
            assert!(
                union
                    .iter()
                    .all(|id| { claimed.iter().any(|task| task.task_id == *id) || *id == leaf }),
                "{queue_rows} rows: walk reached outside {{claimed, leaf}}: {union:?}"
            );
            measured.push((union.len() - claimed.len(), depth, claimed.len()));
        }
        assert_eq!(
            measured[0].0, measured[1].0,
            "closure size beyond the claimed rows must be identical: {measured:?}"
        );
        assert_eq!(
            measured[0].1, measured[1].1,
            "closure depth must be identical across sizes: {measured:?}"
        );
    }
}
